/*
QueueFlow API

Testing WorkerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package queueflow

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/queue-flow/sdk-go"
)

func Test_queueflow_WorkerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkerAPIService CompleteJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.WorkerAPI.CompleteJob(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkerAPIService FailJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.WorkerAPI.FailJob(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkerAPIService HeartbeatJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.WorkerAPI.HeartbeatJob(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkerAPIService LeaseJobs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var queue string

		resp, httpRes, err := apiClient.WorkerAPI.LeaseJobs(context.Background(), queue).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
