/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListJobsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListJobsResponse{}

// ListJobsResponse struct for ListJobsResponse
type ListJobsResponse struct {
	HasMore bool `json:"has_more"`
	Jobs []Job `json:"jobs"`
	Limit int64 `json:"limit"`
	Offset int64 `json:"offset"`
	// Exact total match count. Only present when the request set `include_total=true`; computing it costs a full count over the filtered set, so it is opt-in.
	Total NullableInt64 `json:"total,omitempty"`
}

type _ListJobsResponse ListJobsResponse

// NewListJobsResponse instantiates a new ListJobsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListJobsResponse(hasMore bool, jobs []Job, limit int64, offset int64) *ListJobsResponse {
	this := ListJobsResponse{}
	this.HasMore = hasMore
	this.Jobs = jobs
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewListJobsResponseWithDefaults instantiates a new ListJobsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListJobsResponseWithDefaults() *ListJobsResponse {
	this := ListJobsResponse{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *ListJobsResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListJobsResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetJobs returns the Jobs field value
func (o *ListJobsResponse) GetJobs() []Job {
	if o == nil {
		var ret []Job
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetJobsOk() ([]Job, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *ListJobsResponse) SetJobs(v []Job) {
	o.Jobs = v
}

// GetLimit returns the Limit field value
func (o *ListJobsResponse) GetLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ListJobsResponse) SetLimit(v int64) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *ListJobsResponse) GetOffset() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *ListJobsResponse) GetOffsetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *ListJobsResponse) SetOffset(v int64) {
	o.Offset = v
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListJobsResponse) GetTotal() int64 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int64
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListJobsResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *ListJobsResponse) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt64 and assigns it to the Total field.
func (o *ListJobsResponse) SetTotal(v int64) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *ListJobsResponse) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *ListJobsResponse) UnsetTotal() {
	o.Total.Unset()
}

func (o ListJobsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListJobsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["jobs"] = o.Jobs
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}
	return toSerialize, nil
}

func (o *ListJobsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"jobs",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListJobsResponse := _ListJobsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListJobsResponse)

	if err != nil {
		return err
	}

	*o = ListJobsResponse(varListJobsResponse)

	return err
}

type NullableListJobsResponse struct {
	value *ListJobsResponse
	isSet bool
}

func (v NullableListJobsResponse) Get() *ListJobsResponse {
	return v.value
}

func (v *NullableListJobsResponse) Set(val *ListJobsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListJobsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListJobsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListJobsResponse(val *ListJobsResponse) *NullableListJobsResponse {
	return &NullableListJobsResponse{value: val, isSet: true}
}

func (v NullableListJobsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListJobsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


