/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FailJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FailJobRequest{}

// FailJobRequest Body for `POST /api/v1/jobs/{id}/fail`.
type FailJobRequest struct {
	// Human-readable failure reason.
	Error string `json:"error"`
	// The lease token returned by the lease call.
	LeaseToken string `json:"lease_token"`
	// Whether the engine may retry (subject to the job's max_retries). Defaults to true; send false for permanent failures (e.g. bad input).
	Retryable *bool `json:"retryable,omitempty"`
}

type _FailJobRequest FailJobRequest

// NewFailJobRequest instantiates a new FailJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFailJobRequest(error_ string, leaseToken string) *FailJobRequest {
	this := FailJobRequest{}
	this.Error = error_
	this.LeaseToken = leaseToken
	return &this
}

// NewFailJobRequestWithDefaults instantiates a new FailJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFailJobRequestWithDefaults() *FailJobRequest {
	this := FailJobRequest{}
	return &this
}

// GetError returns the Error field value
func (o *FailJobRequest) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *FailJobRequest) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *FailJobRequest) SetError(v string) {
	o.Error = v
}

// GetLeaseToken returns the LeaseToken field value
func (o *FailJobRequest) GetLeaseToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaseToken
}

// GetLeaseTokenOk returns a tuple with the LeaseToken field value
// and a boolean to check if the value has been set.
func (o *FailJobRequest) GetLeaseTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaseToken, true
}

// SetLeaseToken sets field value
func (o *FailJobRequest) SetLeaseToken(v string) {
	o.LeaseToken = v
}

// GetRetryable returns the Retryable field value if set, zero value otherwise.
func (o *FailJobRequest) GetRetryable() bool {
	if o == nil || IsNil(o.Retryable) {
		var ret bool
		return ret
	}
	return *o.Retryable
}

// GetRetryableOk returns a tuple with the Retryable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FailJobRequest) GetRetryableOk() (*bool, bool) {
	if o == nil || IsNil(o.Retryable) {
		return nil, false
	}
	return o.Retryable, true
}

// HasRetryable returns a boolean if a field has been set.
func (o *FailJobRequest) HasRetryable() bool {
	if o != nil && !IsNil(o.Retryable) {
		return true
	}

	return false
}

// SetRetryable gets a reference to the given bool and assigns it to the Retryable field.
func (o *FailJobRequest) SetRetryable(v bool) {
	o.Retryable = &v
}

func (o FailJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FailJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["lease_token"] = o.LeaseToken
	if !IsNil(o.Retryable) {
		toSerialize["retryable"] = o.Retryable
	}
	return toSerialize, nil
}

func (o *FailJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"lease_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFailJobRequest := _FailJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFailJobRequest)

	if err != nil {
		return err
	}

	*o = FailJobRequest(varFailJobRequest)

	return err
}

type NullableFailJobRequest struct {
	value *FailJobRequest
	isSet bool
}

func (v NullableFailJobRequest) Get() *FailJobRequest {
	return v.value
}

func (v *NullableFailJobRequest) Set(val *FailJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFailJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFailJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFailJobRequest(val *FailJobRequest) *NullableFailJobRequest {
	return &NullableFailJobRequest{value: val, isSet: true}
}

func (v NullableFailJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFailJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


