/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobConfig{}

// JobConfig Per-job execution configuration. All durations are in seconds.
type JobConfig struct {
	// Optional jitter in `0.0..=1.0`. `0.1` => +/-10% randomization of each retry delay, which spreads out thundering-herd retries.
	JitterFactor NullableFloat64 `json:"jitter_factor,omitempty"`
	MaxRetries int32 `json:"max_retries"`
	// Higher is claimed first within a queue; ties break on `scheduled_at`, then `created_at`.
	Priority int32 `json:"priority"`
	RetryBackoff *BackoffStrategy `json:"retry_backoff,omitempty"`
	RetryDelaySecs int64 `json:"retry_delay_secs"`
	RetryMaxDelaySecs int64 `json:"retry_max_delay_secs"`
	TimeoutSecs int64 `json:"timeout_secs"`
}

type _JobConfig JobConfig

// NewJobConfig instantiates a new JobConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobConfig(maxRetries int32, priority int32, retryDelaySecs int64, retryMaxDelaySecs int64, timeoutSecs int64) *JobConfig {
	this := JobConfig{}
	this.MaxRetries = maxRetries
	this.Priority = priority
	this.RetryDelaySecs = retryDelaySecs
	this.RetryMaxDelaySecs = retryMaxDelaySecs
	this.TimeoutSecs = timeoutSecs
	return &this
}

// NewJobConfigWithDefaults instantiates a new JobConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobConfigWithDefaults() *JobConfig {
	this := JobConfig{}
	return &this
}

// GetJitterFactor returns the JitterFactor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobConfig) GetJitterFactor() float64 {
	if o == nil || IsNil(o.JitterFactor.Get()) {
		var ret float64
		return ret
	}
	return *o.JitterFactor.Get()
}

// GetJitterFactorOk returns a tuple with the JitterFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobConfig) GetJitterFactorOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.JitterFactor.Get(), o.JitterFactor.IsSet()
}

// HasJitterFactor returns a boolean if a field has been set.
func (o *JobConfig) HasJitterFactor() bool {
	if o != nil && o.JitterFactor.IsSet() {
		return true
	}

	return false
}

// SetJitterFactor gets a reference to the given NullableFloat64 and assigns it to the JitterFactor field.
func (o *JobConfig) SetJitterFactor(v float64) {
	o.JitterFactor.Set(&v)
}
// SetJitterFactorNil sets the value for JitterFactor to be an explicit nil
func (o *JobConfig) SetJitterFactorNil() {
	o.JitterFactor.Set(nil)
}

// UnsetJitterFactor ensures that no value is present for JitterFactor, not even an explicit nil
func (o *JobConfig) UnsetJitterFactor() {
	o.JitterFactor.Unset()
}

// GetMaxRetries returns the MaxRetries field value
func (o *JobConfig) GetMaxRetries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value
// and a boolean to check if the value has been set.
func (o *JobConfig) GetMaxRetriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxRetries, true
}

// SetMaxRetries sets field value
func (o *JobConfig) SetMaxRetries(v int32) {
	o.MaxRetries = v
}

// GetPriority returns the Priority field value
func (o *JobConfig) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *JobConfig) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *JobConfig) SetPriority(v int32) {
	o.Priority = v
}

// GetRetryBackoff returns the RetryBackoff field value if set, zero value otherwise.
func (o *JobConfig) GetRetryBackoff() BackoffStrategy {
	if o == nil || IsNil(o.RetryBackoff) {
		var ret BackoffStrategy
		return ret
	}
	return *o.RetryBackoff
}

// GetRetryBackoffOk returns a tuple with the RetryBackoff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetRetryBackoffOk() (*BackoffStrategy, bool) {
	if o == nil || IsNil(o.RetryBackoff) {
		return nil, false
	}
	return o.RetryBackoff, true
}

// HasRetryBackoff returns a boolean if a field has been set.
func (o *JobConfig) HasRetryBackoff() bool {
	if o != nil && !IsNil(o.RetryBackoff) {
		return true
	}

	return false
}

// SetRetryBackoff gets a reference to the given BackoffStrategy and assigns it to the RetryBackoff field.
func (o *JobConfig) SetRetryBackoff(v BackoffStrategy) {
	o.RetryBackoff = &v
}

// GetRetryDelaySecs returns the RetryDelaySecs field value
func (o *JobConfig) GetRetryDelaySecs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RetryDelaySecs
}

// GetRetryDelaySecsOk returns a tuple with the RetryDelaySecs field value
// and a boolean to check if the value has been set.
func (o *JobConfig) GetRetryDelaySecsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryDelaySecs, true
}

// SetRetryDelaySecs sets field value
func (o *JobConfig) SetRetryDelaySecs(v int64) {
	o.RetryDelaySecs = v
}

// GetRetryMaxDelaySecs returns the RetryMaxDelaySecs field value
func (o *JobConfig) GetRetryMaxDelaySecs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RetryMaxDelaySecs
}

// GetRetryMaxDelaySecsOk returns a tuple with the RetryMaxDelaySecs field value
// and a boolean to check if the value has been set.
func (o *JobConfig) GetRetryMaxDelaySecsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryMaxDelaySecs, true
}

// SetRetryMaxDelaySecs sets field value
func (o *JobConfig) SetRetryMaxDelaySecs(v int64) {
	o.RetryMaxDelaySecs = v
}

// GetTimeoutSecs returns the TimeoutSecs field value
func (o *JobConfig) GetTimeoutSecs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TimeoutSecs
}

// GetTimeoutSecsOk returns a tuple with the TimeoutSecs field value
// and a boolean to check if the value has been set.
func (o *JobConfig) GetTimeoutSecsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeoutSecs, true
}

// SetTimeoutSecs sets field value
func (o *JobConfig) SetTimeoutSecs(v int64) {
	o.TimeoutSecs = v
}

func (o JobConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.JitterFactor.IsSet() {
		toSerialize["jitter_factor"] = o.JitterFactor.Get()
	}
	toSerialize["max_retries"] = o.MaxRetries
	toSerialize["priority"] = o.Priority
	if !IsNil(o.RetryBackoff) {
		toSerialize["retry_backoff"] = o.RetryBackoff
	}
	toSerialize["retry_delay_secs"] = o.RetryDelaySecs
	toSerialize["retry_max_delay_secs"] = o.RetryMaxDelaySecs
	toSerialize["timeout_secs"] = o.TimeoutSecs
	return toSerialize, nil
}

func (o *JobConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"max_retries",
		"priority",
		"retry_delay_secs",
		"retry_max_delay_secs",
		"timeout_secs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobConfig := _JobConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobConfig)

	if err != nil {
		return err
	}

	*o = JobConfig(varJobConfig)

	return err
}

type NullableJobConfig struct {
	value *JobConfig
	isSet bool
}

func (v NullableJobConfig) Get() *JobConfig {
	return v.value
}

func (v *NullableJobConfig) Set(val *JobConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableJobConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableJobConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobConfig(val *JobConfig) *NullableJobConfig {
	return &NullableJobConfig{value: val, isSet: true}
}

func (v NullableJobConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


