/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowStep{}

// WorkflowStep A node in a workflow DAG. Steps are addressed by their unique `name`; `depends_on` lists the names of steps that must complete first.
type WorkflowStep struct {
	Config NullableJobConfig `json:"config,omitempty"`
	DependsOn []string `json:"depends_on,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Name string `json:"name"`
	OnFailure *OnFailure `json:"on_failure,omitempty"`
	OnSuccess *OnSuccess `json:"on_success,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	TaskName string `json:"task_name"`
}

type _WorkflowStep WorkflowStep

// NewWorkflowStep instantiates a new WorkflowStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowStep(name string, taskName string) *WorkflowStep {
	this := WorkflowStep{}
	this.Name = name
	this.TaskName = taskName
	return &this
}

// NewWorkflowStepWithDefaults instantiates a new WorkflowStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowStepWithDefaults() *WorkflowStep {
	this := WorkflowStep{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowStep) GetConfig() JobConfig {
	if o == nil || IsNil(o.Config.Get()) {
		var ret JobConfig
		return ret
	}
	return *o.Config.Get()
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowStep) GetConfigOk() (*JobConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Config.Get(), o.Config.IsSet()
}

// HasConfig returns a boolean if a field has been set.
func (o *WorkflowStep) HasConfig() bool {
	if o != nil && o.Config.IsSet() {
		return true
	}

	return false
}

// SetConfig gets a reference to the given NullableJobConfig and assigns it to the Config field.
func (o *WorkflowStep) SetConfig(v JobConfig) {
	o.Config.Set(&v)
}
// SetConfigNil sets the value for Config to be an explicit nil
func (o *WorkflowStep) SetConfigNil() {
	o.Config.Set(nil)
}

// UnsetConfig ensures that no value is present for Config, not even an explicit nil
func (o *WorkflowStep) UnsetConfig() {
	o.Config.Unset()
}

// GetDependsOn returns the DependsOn field value if set, zero value otherwise.
func (o *WorkflowStep) GetDependsOn() []string {
	if o == nil || IsNil(o.DependsOn) {
		var ret []string
		return ret
	}
	return o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetDependsOnOk() ([]string, bool) {
	if o == nil || IsNil(o.DependsOn) {
		return nil, false
	}
	return o.DependsOn, true
}

// HasDependsOn returns a boolean if a field has been set.
func (o *WorkflowStep) HasDependsOn() bool {
	if o != nil && !IsNil(o.DependsOn) {
		return true
	}

	return false
}

// SetDependsOn gets a reference to the given []string and assigns it to the DependsOn field.
func (o *WorkflowStep) SetDependsOn(v []string) {
	o.DependsOn = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *WorkflowStep) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *WorkflowStep) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *WorkflowStep) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetName returns the Name field value
func (o *WorkflowStep) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkflowStep) SetName(v string) {
	o.Name = v
}

// GetOnFailure returns the OnFailure field value if set, zero value otherwise.
func (o *WorkflowStep) GetOnFailure() OnFailure {
	if o == nil || IsNil(o.OnFailure) {
		var ret OnFailure
		return ret
	}
	return *o.OnFailure
}

// GetOnFailureOk returns a tuple with the OnFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetOnFailureOk() (*OnFailure, bool) {
	if o == nil || IsNil(o.OnFailure) {
		return nil, false
	}
	return o.OnFailure, true
}

// HasOnFailure returns a boolean if a field has been set.
func (o *WorkflowStep) HasOnFailure() bool {
	if o != nil && !IsNil(o.OnFailure) {
		return true
	}

	return false
}

// SetOnFailure gets a reference to the given OnFailure and assigns it to the OnFailure field.
func (o *WorkflowStep) SetOnFailure(v OnFailure) {
	o.OnFailure = &v
}

// GetOnSuccess returns the OnSuccess field value if set, zero value otherwise.
func (o *WorkflowStep) GetOnSuccess() OnSuccess {
	if o == nil || IsNil(o.OnSuccess) {
		var ret OnSuccess
		return ret
	}
	return *o.OnSuccess
}

// GetOnSuccessOk returns a tuple with the OnSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetOnSuccessOk() (*OnSuccess, bool) {
	if o == nil || IsNil(o.OnSuccess) {
		return nil, false
	}
	return o.OnSuccess, true
}

// HasOnSuccess returns a boolean if a field has been set.
func (o *WorkflowStep) HasOnSuccess() bool {
	if o != nil && !IsNil(o.OnSuccess) {
		return true
	}

	return false
}

// SetOnSuccess gets a reference to the given OnSuccess and assigns it to the OnSuccess field.
func (o *WorkflowStep) SetOnSuccess(v OnSuccess) {
	o.OnSuccess = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *WorkflowStep) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *WorkflowStep) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *WorkflowStep) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetTaskName returns the TaskName field value
func (o *WorkflowStep) GetTaskName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskName, true
}

// SetTaskName sets field value
func (o *WorkflowStep) SetTaskName(v string) {
	o.TaskName = v
}

func (o WorkflowStep) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config.IsSet() {
		toSerialize["config"] = o.Config.Get()
	}
	if !IsNil(o.DependsOn) {
		toSerialize["depends_on"] = o.DependsOn
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.OnFailure) {
		toSerialize["on_failure"] = o.OnFailure
	}
	if !IsNil(o.OnSuccess) {
		toSerialize["on_success"] = o.OnSuccess
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	toSerialize["task_name"] = o.TaskName
	return toSerialize, nil
}

func (o *WorkflowStep) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"task_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowStep := _WorkflowStep{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowStep)

	if err != nil {
		return err
	}

	*o = WorkflowStep(varWorkflowStep)

	return err
}

type NullableWorkflowStep struct {
	value *WorkflowStep
	isSet bool
}

func (v NullableWorkflowStep) Get() *WorkflowStep {
	return v.value
}

func (v *NullableWorkflowStep) Set(val *WorkflowStep) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowStep) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowStep(val *WorkflowStep) *NullableWorkflowStep {
	return &NullableWorkflowStep{value: val, isSet: true}
}

func (v NullableWorkflowStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


