/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
)

// checks if the JobConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobConfig{}

// JobConfig Per-job execution configuration. All durations are in seconds.  Deserialization is partial-friendly: any omitted field takes its [`JobConfig::default`] value (via per-field serde defaults), so workflow-step and cron config overrides can name just the fields they change, and out-of-band rows with sparse `config` JSONB still load. Per-field functions rather than a struct-level `#[serde(default)]`: the struct-level form makes utoipa attach a `default` beside the `BackoffStrategy` `$ref`, which forces a synthetic wrapper type into every generated SDK.
type JobConfig struct {
	// Optional jitter in `0.0..=1.0`. `0.1` => +/-10% randomization of each retry delay, which spreads out thundering-herd retries.
	JitterFactor NullableFloat64 `json:"jitter_factor,omitempty"`
	MaxRetries *int32 `json:"max_retries,omitempty"`
	// Higher is claimed first within a queue; ties break on `scheduled_at`, then `created_at`.
	Priority *int32 `json:"priority,omitempty"`
	RetryBackoff *BackoffStrategy `json:"retry_backoff,omitempty"`
	RetryDelaySecs *int64 `json:"retry_delay_secs,omitempty"`
	RetryMaxDelaySecs *int64 `json:"retry_max_delay_secs,omitempty"`
	TimeoutSecs *int64 `json:"timeout_secs,omitempty"`
}

// NewJobConfig instantiates a new JobConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobConfig() *JobConfig {
	this := JobConfig{}
	return &this
}

// NewJobConfigWithDefaults instantiates a new JobConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobConfigWithDefaults() *JobConfig {
	this := JobConfig{}
	return &this
}

// GetJitterFactor returns the JitterFactor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobConfig) GetJitterFactor() float64 {
	if o == nil || IsNil(o.JitterFactor.Get()) {
		var ret float64
		return ret
	}
	return *o.JitterFactor.Get()
}

// GetJitterFactorOk returns a tuple with the JitterFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobConfig) GetJitterFactorOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.JitterFactor.Get(), o.JitterFactor.IsSet()
}

// HasJitterFactor returns a boolean if a field has been set.
func (o *JobConfig) HasJitterFactor() bool {
	if o != nil && o.JitterFactor.IsSet() {
		return true
	}

	return false
}

// SetJitterFactor gets a reference to the given NullableFloat64 and assigns it to the JitterFactor field.
func (o *JobConfig) SetJitterFactor(v float64) {
	o.JitterFactor.Set(&v)
}
// SetJitterFactorNil sets the value for JitterFactor to be an explicit nil
func (o *JobConfig) SetJitterFactorNil() {
	o.JitterFactor.Set(nil)
}

// UnsetJitterFactor ensures that no value is present for JitterFactor, not even an explicit nil
func (o *JobConfig) UnsetJitterFactor() {
	o.JitterFactor.Unset()
}

// GetMaxRetries returns the MaxRetries field value if set, zero value otherwise.
func (o *JobConfig) GetMaxRetries() int32 {
	if o == nil || IsNil(o.MaxRetries) {
		var ret int32
		return ret
	}
	return *o.MaxRetries
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetMaxRetriesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxRetries) {
		return nil, false
	}
	return o.MaxRetries, true
}

// HasMaxRetries returns a boolean if a field has been set.
func (o *JobConfig) HasMaxRetries() bool {
	if o != nil && !IsNil(o.MaxRetries) {
		return true
	}

	return false
}

// SetMaxRetries gets a reference to the given int32 and assigns it to the MaxRetries field.
func (o *JobConfig) SetMaxRetries(v int32) {
	o.MaxRetries = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *JobConfig) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *JobConfig) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *JobConfig) SetPriority(v int32) {
	o.Priority = &v
}

// GetRetryBackoff returns the RetryBackoff field value if set, zero value otherwise.
func (o *JobConfig) GetRetryBackoff() BackoffStrategy {
	if o == nil || IsNil(o.RetryBackoff) {
		var ret BackoffStrategy
		return ret
	}
	return *o.RetryBackoff
}

// GetRetryBackoffOk returns a tuple with the RetryBackoff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetRetryBackoffOk() (*BackoffStrategy, bool) {
	if o == nil || IsNil(o.RetryBackoff) {
		return nil, false
	}
	return o.RetryBackoff, true
}

// HasRetryBackoff returns a boolean if a field has been set.
func (o *JobConfig) HasRetryBackoff() bool {
	if o != nil && !IsNil(o.RetryBackoff) {
		return true
	}

	return false
}

// SetRetryBackoff gets a reference to the given BackoffStrategy and assigns it to the RetryBackoff field.
func (o *JobConfig) SetRetryBackoff(v BackoffStrategy) {
	o.RetryBackoff = &v
}

// GetRetryDelaySecs returns the RetryDelaySecs field value if set, zero value otherwise.
func (o *JobConfig) GetRetryDelaySecs() int64 {
	if o == nil || IsNil(o.RetryDelaySecs) {
		var ret int64
		return ret
	}
	return *o.RetryDelaySecs
}

// GetRetryDelaySecsOk returns a tuple with the RetryDelaySecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetRetryDelaySecsOk() (*int64, bool) {
	if o == nil || IsNil(o.RetryDelaySecs) {
		return nil, false
	}
	return o.RetryDelaySecs, true
}

// HasRetryDelaySecs returns a boolean if a field has been set.
func (o *JobConfig) HasRetryDelaySecs() bool {
	if o != nil && !IsNil(o.RetryDelaySecs) {
		return true
	}

	return false
}

// SetRetryDelaySecs gets a reference to the given int64 and assigns it to the RetryDelaySecs field.
func (o *JobConfig) SetRetryDelaySecs(v int64) {
	o.RetryDelaySecs = &v
}

// GetRetryMaxDelaySecs returns the RetryMaxDelaySecs field value if set, zero value otherwise.
func (o *JobConfig) GetRetryMaxDelaySecs() int64 {
	if o == nil || IsNil(o.RetryMaxDelaySecs) {
		var ret int64
		return ret
	}
	return *o.RetryMaxDelaySecs
}

// GetRetryMaxDelaySecsOk returns a tuple with the RetryMaxDelaySecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetRetryMaxDelaySecsOk() (*int64, bool) {
	if o == nil || IsNil(o.RetryMaxDelaySecs) {
		return nil, false
	}
	return o.RetryMaxDelaySecs, true
}

// HasRetryMaxDelaySecs returns a boolean if a field has been set.
func (o *JobConfig) HasRetryMaxDelaySecs() bool {
	if o != nil && !IsNil(o.RetryMaxDelaySecs) {
		return true
	}

	return false
}

// SetRetryMaxDelaySecs gets a reference to the given int64 and assigns it to the RetryMaxDelaySecs field.
func (o *JobConfig) SetRetryMaxDelaySecs(v int64) {
	o.RetryMaxDelaySecs = &v
}

// GetTimeoutSecs returns the TimeoutSecs field value if set, zero value otherwise.
func (o *JobConfig) GetTimeoutSecs() int64 {
	if o == nil || IsNil(o.TimeoutSecs) {
		var ret int64
		return ret
	}
	return *o.TimeoutSecs
}

// GetTimeoutSecsOk returns a tuple with the TimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobConfig) GetTimeoutSecsOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeoutSecs) {
		return nil, false
	}
	return o.TimeoutSecs, true
}

// HasTimeoutSecs returns a boolean if a field has been set.
func (o *JobConfig) HasTimeoutSecs() bool {
	if o != nil && !IsNil(o.TimeoutSecs) {
		return true
	}

	return false
}

// SetTimeoutSecs gets a reference to the given int64 and assigns it to the TimeoutSecs field.
func (o *JobConfig) SetTimeoutSecs(v int64) {
	o.TimeoutSecs = &v
}

func (o JobConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.JitterFactor.IsSet() {
		toSerialize["jitter_factor"] = o.JitterFactor.Get()
	}
	if !IsNil(o.MaxRetries) {
		toSerialize["max_retries"] = o.MaxRetries
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.RetryBackoff) {
		toSerialize["retry_backoff"] = o.RetryBackoff
	}
	if !IsNil(o.RetryDelaySecs) {
		toSerialize["retry_delay_secs"] = o.RetryDelaySecs
	}
	if !IsNil(o.RetryMaxDelaySecs) {
		toSerialize["retry_max_delay_secs"] = o.RetryMaxDelaySecs
	}
	if !IsNil(o.TimeoutSecs) {
		toSerialize["timeout_secs"] = o.TimeoutSecs
	}
	return toSerialize, nil
}

type NullableJobConfig struct {
	value *JobConfig
	isSet bool
}

func (v NullableJobConfig) Get() *JobConfig {
	return v.value
}

func (v *NullableJobConfig) Set(val *JobConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableJobConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableJobConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobConfig(val *JobConfig) *NullableJobConfig {
	return &NullableJobConfig{value: val, isSet: true}
}

func (v NullableJobConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


