/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ErrorBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorBody{}

// ErrorBody struct for ErrorBody
type ErrorBody struct {
	Error string `json:"error"`
	Timestamp time.Time `json:"timestamp"`
}

type _ErrorBody ErrorBody

// NewErrorBody instantiates a new ErrorBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorBody(error_ string, timestamp time.Time) *ErrorBody {
	this := ErrorBody{}
	this.Error = error_
	this.Timestamp = timestamp
	return &this
}

// NewErrorBodyWithDefaults instantiates a new ErrorBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorBodyWithDefaults() *ErrorBody {
	this := ErrorBody{}
	return &this
}

// GetError returns the Error field value
func (o *ErrorBody) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ErrorBody) SetError(v string) {
	o.Error = v
}

// GetTimestamp returns the Timestamp field value
func (o *ErrorBody) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ErrorBody) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o ErrorBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *ErrorBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorBody := _ErrorBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorBody)

	if err != nil {
		return err
	}

	*o = ErrorBody(varErrorBody)

	return err
}

type NullableErrorBody struct {
	value *ErrorBody
	isSet bool
}

func (v NullableErrorBody) Get() *ErrorBody {
	return v.value
}

func (v *NullableErrorBody) Set(val *ErrorBody) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorBody) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorBody(val *ErrorBody) *NullableErrorBody {
	return &NullableErrorBody{value: val, isSet: true}
}

func (v NullableErrorBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


