/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeadLetter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeadLetter{}

// DeadLetter A dead-lettered job: a terminal failure recorded for inspection and replay. The original job row remains (subject to retention); this entry captures why it died and, once replayed, which fresh job took its place.
type DeadLetter struct {
	CreatedAt time.Time `json:"created_at"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	Id int64 `json:"id"`
	JobId string `json:"job_id"`
	QueueName NullableString `json:"queue_name,omitempty"`
	// Why the job dead-lettered: `max_attempts_exceeded`, `non_retryable`, or `handler_not_found`.
	Reason string `json:"reason"`
	// The fresh job created by the replay.
	ReplayJobId NullableString `json:"replay_job_id,omitempty"`
	// Set once this entry has been replayed; a dead letter replays at most once.
	ReplayedAt NullableTime `json:"replayed_at,omitempty"`
	TaskName NullableString `json:"task_name,omitempty"`
	TenantId NullableString `json:"tenant_id,omitempty"`
}

type _DeadLetter DeadLetter

// NewDeadLetter instantiates a new DeadLetter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeadLetter(createdAt time.Time, id int64, jobId string, reason string) *DeadLetter {
	this := DeadLetter{}
	this.CreatedAt = createdAt
	this.Id = id
	this.JobId = jobId
	this.Reason = reason
	return &this
}

// NewDeadLetterWithDefaults instantiates a new DeadLetter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeadLetterWithDefaults() *DeadLetter {
	this := DeadLetter{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeadLetter) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeadLetter) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeadLetter) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeadLetter) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeadLetter) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *DeadLetter) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *DeadLetter) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *DeadLetter) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *DeadLetter) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetId returns the Id field value
func (o *DeadLetter) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeadLetter) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeadLetter) SetId(v int64) {
	o.Id = v
}

// GetJobId returns the JobId field value
func (o *DeadLetter) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *DeadLetter) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *DeadLetter) SetJobId(v string) {
	o.JobId = v
}

// GetQueueName returns the QueueName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeadLetter) GetQueueName() string {
	if o == nil || IsNil(o.QueueName.Get()) {
		var ret string
		return ret
	}
	return *o.QueueName.Get()
}

// GetQueueNameOk returns a tuple with the QueueName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeadLetter) GetQueueNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueueName.Get(), o.QueueName.IsSet()
}

// HasQueueName returns a boolean if a field has been set.
func (o *DeadLetter) HasQueueName() bool {
	if o != nil && o.QueueName.IsSet() {
		return true
	}

	return false
}

// SetQueueName gets a reference to the given NullableString and assigns it to the QueueName field.
func (o *DeadLetter) SetQueueName(v string) {
	o.QueueName.Set(&v)
}
// SetQueueNameNil sets the value for QueueName to be an explicit nil
func (o *DeadLetter) SetQueueNameNil() {
	o.QueueName.Set(nil)
}

// UnsetQueueName ensures that no value is present for QueueName, not even an explicit nil
func (o *DeadLetter) UnsetQueueName() {
	o.QueueName.Unset()
}

// GetReason returns the Reason field value
func (o *DeadLetter) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *DeadLetter) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *DeadLetter) SetReason(v string) {
	o.Reason = v
}

// GetReplayJobId returns the ReplayJobId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeadLetter) GetReplayJobId() string {
	if o == nil || IsNil(o.ReplayJobId.Get()) {
		var ret string
		return ret
	}
	return *o.ReplayJobId.Get()
}

// GetReplayJobIdOk returns a tuple with the ReplayJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeadLetter) GetReplayJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReplayJobId.Get(), o.ReplayJobId.IsSet()
}

// HasReplayJobId returns a boolean if a field has been set.
func (o *DeadLetter) HasReplayJobId() bool {
	if o != nil && o.ReplayJobId.IsSet() {
		return true
	}

	return false
}

// SetReplayJobId gets a reference to the given NullableString and assigns it to the ReplayJobId field.
func (o *DeadLetter) SetReplayJobId(v string) {
	o.ReplayJobId.Set(&v)
}
// SetReplayJobIdNil sets the value for ReplayJobId to be an explicit nil
func (o *DeadLetter) SetReplayJobIdNil() {
	o.ReplayJobId.Set(nil)
}

// UnsetReplayJobId ensures that no value is present for ReplayJobId, not even an explicit nil
func (o *DeadLetter) UnsetReplayJobId() {
	o.ReplayJobId.Unset()
}

// GetReplayedAt returns the ReplayedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeadLetter) GetReplayedAt() time.Time {
	if o == nil || IsNil(o.ReplayedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ReplayedAt.Get()
}

// GetReplayedAtOk returns a tuple with the ReplayedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeadLetter) GetReplayedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReplayedAt.Get(), o.ReplayedAt.IsSet()
}

// HasReplayedAt returns a boolean if a field has been set.
func (o *DeadLetter) HasReplayedAt() bool {
	if o != nil && o.ReplayedAt.IsSet() {
		return true
	}

	return false
}

// SetReplayedAt gets a reference to the given NullableTime and assigns it to the ReplayedAt field.
func (o *DeadLetter) SetReplayedAt(v time.Time) {
	o.ReplayedAt.Set(&v)
}
// SetReplayedAtNil sets the value for ReplayedAt to be an explicit nil
func (o *DeadLetter) SetReplayedAtNil() {
	o.ReplayedAt.Set(nil)
}

// UnsetReplayedAt ensures that no value is present for ReplayedAt, not even an explicit nil
func (o *DeadLetter) UnsetReplayedAt() {
	o.ReplayedAt.Unset()
}

// GetTaskName returns the TaskName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeadLetter) GetTaskName() string {
	if o == nil || IsNil(o.TaskName.Get()) {
		var ret string
		return ret
	}
	return *o.TaskName.Get()
}

// GetTaskNameOk returns a tuple with the TaskName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeadLetter) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskName.Get(), o.TaskName.IsSet()
}

// HasTaskName returns a boolean if a field has been set.
func (o *DeadLetter) HasTaskName() bool {
	if o != nil && o.TaskName.IsSet() {
		return true
	}

	return false
}

// SetTaskName gets a reference to the given NullableString and assigns it to the TaskName field.
func (o *DeadLetter) SetTaskName(v string) {
	o.TaskName.Set(&v)
}
// SetTaskNameNil sets the value for TaskName to be an explicit nil
func (o *DeadLetter) SetTaskNameNil() {
	o.TaskName.Set(nil)
}

// UnsetTaskName ensures that no value is present for TaskName, not even an explicit nil
func (o *DeadLetter) UnsetTaskName() {
	o.TaskName.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeadLetter) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeadLetter) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *DeadLetter) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *DeadLetter) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *DeadLetter) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *DeadLetter) UnsetTenantId() {
	o.TenantId.Unset()
}

func (o DeadLetter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeadLetter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["job_id"] = o.JobId
	if o.QueueName.IsSet() {
		toSerialize["queue_name"] = o.QueueName.Get()
	}
	toSerialize["reason"] = o.Reason
	if o.ReplayJobId.IsSet() {
		toSerialize["replay_job_id"] = o.ReplayJobId.Get()
	}
	if o.ReplayedAt.IsSet() {
		toSerialize["replayed_at"] = o.ReplayedAt.Get()
	}
	if o.TaskName.IsSet() {
		toSerialize["task_name"] = o.TaskName.Get()
	}
	if o.TenantId.IsSet() {
		toSerialize["tenant_id"] = o.TenantId.Get()
	}
	return toSerialize, nil
}

func (o *DeadLetter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"job_id",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeadLetter := _DeadLetter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeadLetter)

	if err != nil {
		return err
	}

	*o = DeadLetter(varDeadLetter)

	return err
}

type NullableDeadLetter struct {
	value *DeadLetter
	isSet bool
}

func (v NullableDeadLetter) Get() *DeadLetter {
	return v.value
}

func (v *NullableDeadLetter) Set(val *DeadLetter) {
	v.value = val
	v.isSet = true
}

func (v NullableDeadLetter) IsSet() bool {
	return v.isSet
}

func (v *NullableDeadLetter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeadLetter(val *DeadLetter) *NullableDeadLetter {
	return &NullableDeadLetter{value: val, isSet: true}
}

func (v NullableDeadLetter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeadLetter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


