/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWorkflowRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowRequest{}

// CreateWorkflowRequest Request body for creating a workflow. Shared by the builder DSL and the API so callers and SDKs use the same contract.
type CreateWorkflowRequest struct {
	Context map[string]interface{} `json:"context,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Name string `json:"name"`
	Steps []WorkflowStep `json:"steps"`
}

type _CreateWorkflowRequest CreateWorkflowRequest

// NewCreateWorkflowRequest instantiates a new CreateWorkflowRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowRequest(name string, steps []WorkflowStep) *CreateWorkflowRequest {
	this := CreateWorkflowRequest{}
	this.Name = name
	this.Steps = steps
	return &this
}

// NewCreateWorkflowRequestWithDefaults instantiates a new CreateWorkflowRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowRequestWithDefaults() *CreateWorkflowRequest {
	this := CreateWorkflowRequest{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *CreateWorkflowRequest) GetContext() map[string]interface{} {
	if o == nil || IsNil(o.Context) {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRequest) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return map[string]interface{}{}, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *CreateWorkflowRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *CreateWorkflowRequest) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateWorkflowRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateWorkflowRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateWorkflowRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetName returns the Name field value
func (o *CreateWorkflowRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateWorkflowRequest) SetName(v string) {
	o.Name = v
}

// GetSteps returns the Steps field value
func (o *CreateWorkflowRequest) GetSteps() []WorkflowStep {
	if o == nil {
		var ret []WorkflowStep
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowRequest) GetStepsOk() ([]WorkflowStep, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *CreateWorkflowRequest) SetSteps(v []WorkflowStep) {
	o.Steps = v
}

func (o CreateWorkflowRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	toSerialize["steps"] = o.Steps
	return toSerialize, nil
}

func (o *CreateWorkflowRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"steps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkflowRequest := _CreateWorkflowRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkflowRequest)

	if err != nil {
		return err
	}

	*o = CreateWorkflowRequest(varCreateWorkflowRequest)

	return err
}

type NullableCreateWorkflowRequest struct {
	value *CreateWorkflowRequest
	isSet bool
}

func (v NullableCreateWorkflowRequest) Get() *CreateWorkflowRequest {
	return v.value
}

func (v *NullableCreateWorkflowRequest) Set(val *CreateWorkflowRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowRequest(val *CreateWorkflowRequest) *NullableCreateWorkflowRequest {
	return &NullableCreateWorkflowRequest{value: val, isSet: true}
}

func (v NullableCreateWorkflowRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


