/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListDeadLettersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDeadLettersResponse{}

// ListDeadLettersResponse struct for ListDeadLettersResponse
type ListDeadLettersResponse struct {
	DeadLetters []DeadLetter `json:"dead_letters"`
	HasMore bool `json:"has_more"`
	Limit int64 `json:"limit"`
	Offset int64 `json:"offset"`
	// Exact total match count; only present when `include_total=true`.
	Total NullableInt64 `json:"total,omitempty"`
}

type _ListDeadLettersResponse ListDeadLettersResponse

// NewListDeadLettersResponse instantiates a new ListDeadLettersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDeadLettersResponse(deadLetters []DeadLetter, hasMore bool, limit int64, offset int64) *ListDeadLettersResponse {
	this := ListDeadLettersResponse{}
	this.DeadLetters = deadLetters
	this.HasMore = hasMore
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewListDeadLettersResponseWithDefaults instantiates a new ListDeadLettersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeadLettersResponseWithDefaults() *ListDeadLettersResponse {
	this := ListDeadLettersResponse{}
	return &this
}

// GetDeadLetters returns the DeadLetters field value
func (o *ListDeadLettersResponse) GetDeadLetters() []DeadLetter {
	if o == nil {
		var ret []DeadLetter
		return ret
	}

	return o.DeadLetters
}

// GetDeadLettersOk returns a tuple with the DeadLetters field value
// and a boolean to check if the value has been set.
func (o *ListDeadLettersResponse) GetDeadLettersOk() ([]DeadLetter, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeadLetters, true
}

// SetDeadLetters sets field value
func (o *ListDeadLettersResponse) SetDeadLetters(v []DeadLetter) {
	o.DeadLetters = v
}

// GetHasMore returns the HasMore field value
func (o *ListDeadLettersResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListDeadLettersResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListDeadLettersResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetLimit returns the Limit field value
func (o *ListDeadLettersResponse) GetLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ListDeadLettersResponse) GetLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ListDeadLettersResponse) SetLimit(v int64) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *ListDeadLettersResponse) GetOffset() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *ListDeadLettersResponse) GetOffsetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *ListDeadLettersResponse) SetOffset(v int64) {
	o.Offset = v
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDeadLettersResponse) GetTotal() int64 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int64
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDeadLettersResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *ListDeadLettersResponse) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt64 and assigns it to the Total field.
func (o *ListDeadLettersResponse) SetTotal(v int64) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *ListDeadLettersResponse) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *ListDeadLettersResponse) UnsetTotal() {
	o.Total.Unset()
}

func (o ListDeadLettersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDeadLettersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dead_letters"] = o.DeadLetters
	toSerialize["has_more"] = o.HasMore
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}
	return toSerialize, nil
}

func (o *ListDeadLettersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dead_letters",
		"has_more",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDeadLettersResponse := _ListDeadLettersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDeadLettersResponse)

	if err != nil {
		return err
	}

	*o = ListDeadLettersResponse(varListDeadLettersResponse)

	return err
}

type NullableListDeadLettersResponse struct {
	value *ListDeadLettersResponse
	isSet bool
}

func (v NullableListDeadLettersResponse) Get() *ListDeadLettersResponse {
	return v.value
}

func (v *NullableListDeadLettersResponse) Set(val *ListDeadLettersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeadLettersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeadLettersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeadLettersResponse(val *ListDeadLettersResponse) *NullableListDeadLettersResponse {
	return &NullableListDeadLettersResponse{value: val, isSet: true}
}

func (v NullableListDeadLettersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeadLettersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


