/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBatchJobsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBatchJobsRequest{}

// CreateBatchJobsRequest struct for CreateBatchJobsRequest
type CreateBatchJobsRequest struct {
	Jobs []CreateJobRequest `json:"jobs"`
}

type _CreateBatchJobsRequest CreateBatchJobsRequest

// NewCreateBatchJobsRequest instantiates a new CreateBatchJobsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBatchJobsRequest(jobs []CreateJobRequest) *CreateBatchJobsRequest {
	this := CreateBatchJobsRequest{}
	this.Jobs = jobs
	return &this
}

// NewCreateBatchJobsRequestWithDefaults instantiates a new CreateBatchJobsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBatchJobsRequestWithDefaults() *CreateBatchJobsRequest {
	this := CreateBatchJobsRequest{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *CreateBatchJobsRequest) GetJobs() []CreateJobRequest {
	if o == nil {
		var ret []CreateJobRequest
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *CreateBatchJobsRequest) GetJobsOk() ([]CreateJobRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *CreateBatchJobsRequest) SetJobs(v []CreateJobRequest) {
	o.Jobs = v
}

func (o CreateBatchJobsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBatchJobsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs
	return toSerialize, nil
}

func (o *CreateBatchJobsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBatchJobsRequest := _CreateBatchJobsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBatchJobsRequest)

	if err != nil {
		return err
	}

	*o = CreateBatchJobsRequest(varCreateBatchJobsRequest)

	return err
}

type NullableCreateBatchJobsRequest struct {
	value *CreateBatchJobsRequest
	isSet bool
}

func (v NullableCreateBatchJobsRequest) Get() *CreateBatchJobsRequest {
	return v.value
}

func (v *NullableCreateBatchJobsRequest) Set(val *CreateBatchJobsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBatchJobsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBatchJobsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBatchJobsRequest(val *CreateBatchJobsRequest) *NullableCreateBatchJobsRequest {
	return &NullableCreateBatchJobsRequest{value: val, isSet: true}
}

func (v NullableCreateBatchJobsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBatchJobsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


