/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowStepState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowStepState{}

// WorkflowStepState Runtime status of one workflow step (the live progress view).
type WorkflowStepState struct {
	// The job executing this step, once one has been scheduled.
	JobId NullableString `json:"job_id,omitempty"`
	// The step's name (its address within the workflow).
	Name string `json:"name"`
	Status StepStatus `json:"status"`
}

type _WorkflowStepState WorkflowStepState

// NewWorkflowStepState instantiates a new WorkflowStepState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowStepState(name string, status StepStatus) *WorkflowStepState {
	this := WorkflowStepState{}
	this.Name = name
	this.Status = status
	return &this
}

// NewWorkflowStepStateWithDefaults instantiates a new WorkflowStepState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowStepStateWithDefaults() *WorkflowStepState {
	this := WorkflowStepState{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowStepState) GetJobId() string {
	if o == nil || IsNil(o.JobId.Get()) {
		var ret string
		return ret
	}
	return *o.JobId.Get()
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowStepState) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobId.Get(), o.JobId.IsSet()
}

// HasJobId returns a boolean if a field has been set.
func (o *WorkflowStepState) HasJobId() bool {
	if o != nil && o.JobId.IsSet() {
		return true
	}

	return false
}

// SetJobId gets a reference to the given NullableString and assigns it to the JobId field.
func (o *WorkflowStepState) SetJobId(v string) {
	o.JobId.Set(&v)
}
// SetJobIdNil sets the value for JobId to be an explicit nil
func (o *WorkflowStepState) SetJobIdNil() {
	o.JobId.Set(nil)
}

// UnsetJobId ensures that no value is present for JobId, not even an explicit nil
func (o *WorkflowStepState) UnsetJobId() {
	o.JobId.Unset()
}

// GetName returns the Name field value
func (o *WorkflowStepState) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkflowStepState) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkflowStepState) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *WorkflowStepState) GetStatus() StepStatus {
	if o == nil {
		var ret StepStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WorkflowStepState) GetStatusOk() (*StepStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WorkflowStepState) SetStatus(v StepStatus) {
	o.Status = v
}

func (o WorkflowStepState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowStepState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.JobId.IsSet() {
		toSerialize["job_id"] = o.JobId.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *WorkflowStepState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowStepState := _WorkflowStepState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowStepState)

	if err != nil {
		return err
	}

	*o = WorkflowStepState(varWorkflowStepState)

	return err
}

type NullableWorkflowStepState struct {
	value *WorkflowStepState
	isSet bool
}

func (v NullableWorkflowStepState) Get() *WorkflowStepState {
	return v.value
}

func (v *NullableWorkflowStepState) Set(val *WorkflowStepState) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowStepState) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowStepState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowStepState(val *WorkflowStepState) *NullableWorkflowStepState {
	return &NullableWorkflowStepState{value: val, isSet: true}
}

func (v NullableWorkflowStepState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowStepState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


