/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReplayDeadLetterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplayDeadLetterResponse{}

// ReplayDeadLetterResponse struct for ReplayDeadLetterResponse
type ReplayDeadLetterResponse struct {
	// The fresh job created from the dead-lettered one.
	JobId string `json:"job_id"`
}

type _ReplayDeadLetterResponse ReplayDeadLetterResponse

// NewReplayDeadLetterResponse instantiates a new ReplayDeadLetterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplayDeadLetterResponse(jobId string) *ReplayDeadLetterResponse {
	this := ReplayDeadLetterResponse{}
	this.JobId = jobId
	return &this
}

// NewReplayDeadLetterResponseWithDefaults instantiates a new ReplayDeadLetterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplayDeadLetterResponseWithDefaults() *ReplayDeadLetterResponse {
	this := ReplayDeadLetterResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *ReplayDeadLetterResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *ReplayDeadLetterResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *ReplayDeadLetterResponse) SetJobId(v string) {
	o.JobId = v
}

func (o ReplayDeadLetterResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplayDeadLetterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	return toSerialize, nil
}

func (o *ReplayDeadLetterResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReplayDeadLetterResponse := _ReplayDeadLetterResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReplayDeadLetterResponse)

	if err != nil {
		return err
	}

	*o = ReplayDeadLetterResponse(varReplayDeadLetterResponse)

	return err
}

type NullableReplayDeadLetterResponse struct {
	value *ReplayDeadLetterResponse
	isSet bool
}

func (v NullableReplayDeadLetterResponse) Get() *ReplayDeadLetterResponse {
	return v.value
}

func (v *NullableReplayDeadLetterResponse) Set(val *ReplayDeadLetterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReplayDeadLetterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReplayDeadLetterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplayDeadLetterResponse(val *ReplayDeadLetterResponse) *NullableReplayDeadLetterResponse {
	return &NullableReplayDeadLetterResponse{value: val, isSet: true}
}

func (v NullableReplayDeadLetterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplayDeadLetterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


