/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCronRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCronRequest{}

// CreateCronRequest Request body for creating a cron schedule.
type CreateCronRequest struct {
	Config NullableJobConfig `json:"config,omitempty"`
	// 5-field crontab (UTC); 6/7 fields with leading seconds also accepted.
	CronExpr string `json:"cron_expr"`
	// Unique per tenant.
	Name string `json:"name"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	Queue NullableString `json:"queue,omitempty"`
	TaskName string `json:"task_name"`
}

type _CreateCronRequest CreateCronRequest

// NewCreateCronRequest instantiates a new CreateCronRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCronRequest(cronExpr string, name string, taskName string) *CreateCronRequest {
	this := CreateCronRequest{}
	this.CronExpr = cronExpr
	this.Name = name
	this.TaskName = taskName
	return &this
}

// NewCreateCronRequestWithDefaults instantiates a new CreateCronRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCronRequestWithDefaults() *CreateCronRequest {
	this := CreateCronRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCronRequest) GetConfig() JobConfig {
	if o == nil || IsNil(o.Config.Get()) {
		var ret JobConfig
		return ret
	}
	return *o.Config.Get()
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCronRequest) GetConfigOk() (*JobConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Config.Get(), o.Config.IsSet()
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateCronRequest) HasConfig() bool {
	if o != nil && o.Config.IsSet() {
		return true
	}

	return false
}

// SetConfig gets a reference to the given NullableJobConfig and assigns it to the Config field.
func (o *CreateCronRequest) SetConfig(v JobConfig) {
	o.Config.Set(&v)
}
// SetConfigNil sets the value for Config to be an explicit nil
func (o *CreateCronRequest) SetConfigNil() {
	o.Config.Set(nil)
}

// UnsetConfig ensures that no value is present for Config, not even an explicit nil
func (o *CreateCronRequest) UnsetConfig() {
	o.Config.Unset()
}

// GetCronExpr returns the CronExpr field value
func (o *CreateCronRequest) GetCronExpr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CronExpr
}

// GetCronExprOk returns a tuple with the CronExpr field value
// and a boolean to check if the value has been set.
func (o *CreateCronRequest) GetCronExprOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CronExpr, true
}

// SetCronExpr sets field value
func (o *CreateCronRequest) SetCronExpr(v string) {
	o.CronExpr = v
}

// GetName returns the Name field value
func (o *CreateCronRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCronRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCronRequest) SetName(v string) {
	o.Name = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *CreateCronRequest) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCronRequest) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *CreateCronRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *CreateCronRequest) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetQueue returns the Queue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCronRequest) GetQueue() string {
	if o == nil || IsNil(o.Queue.Get()) {
		var ret string
		return ret
	}
	return *o.Queue.Get()
}

// GetQueueOk returns a tuple with the Queue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCronRequest) GetQueueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queue.Get(), o.Queue.IsSet()
}

// HasQueue returns a boolean if a field has been set.
func (o *CreateCronRequest) HasQueue() bool {
	if o != nil && o.Queue.IsSet() {
		return true
	}

	return false
}

// SetQueue gets a reference to the given NullableString and assigns it to the Queue field.
func (o *CreateCronRequest) SetQueue(v string) {
	o.Queue.Set(&v)
}
// SetQueueNil sets the value for Queue to be an explicit nil
func (o *CreateCronRequest) SetQueueNil() {
	o.Queue.Set(nil)
}

// UnsetQueue ensures that no value is present for Queue, not even an explicit nil
func (o *CreateCronRequest) UnsetQueue() {
	o.Queue.Unset()
}

// GetTaskName returns the TaskName field value
func (o *CreateCronRequest) GetTaskName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value
// and a boolean to check if the value has been set.
func (o *CreateCronRequest) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskName, true
}

// SetTaskName sets field value
func (o *CreateCronRequest) SetTaskName(v string) {
	o.TaskName = v
}

func (o CreateCronRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCronRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config.IsSet() {
		toSerialize["config"] = o.Config.Get()
	}
	toSerialize["cron_expr"] = o.CronExpr
	toSerialize["name"] = o.Name
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if o.Queue.IsSet() {
		toSerialize["queue"] = o.Queue.Get()
	}
	toSerialize["task_name"] = o.TaskName
	return toSerialize, nil
}

func (o *CreateCronRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cron_expr",
		"name",
		"task_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCronRequest := _CreateCronRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCronRequest)

	if err != nil {
		return err
	}

	*o = CreateCronRequest(varCreateCronRequest)

	return err
}

type NullableCreateCronRequest struct {
	value *CreateCronRequest
	isSet bool
}

func (v NullableCreateCronRequest) Get() *CreateCronRequest {
	return v.value
}

func (v *NullableCreateCronRequest) Set(val *CreateCronRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCronRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCronRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCronRequest(val *CreateCronRequest) *NullableCreateCronRequest {
	return &NullableCreateCronRequest{value: val, isSet: true}
}

func (v NullableCreateCronRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCronRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


