/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowStepStatesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowStepStatesResponse{}

// WorkflowStepStatesResponse struct for WorkflowStepStatesResponse
type WorkflowStepStatesResponse struct {
	// One entry per step, in declaration order.
	Steps []WorkflowStepState `json:"steps"`
}

type _WorkflowStepStatesResponse WorkflowStepStatesResponse

// NewWorkflowStepStatesResponse instantiates a new WorkflowStepStatesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowStepStatesResponse(steps []WorkflowStepState) *WorkflowStepStatesResponse {
	this := WorkflowStepStatesResponse{}
	this.Steps = steps
	return &this
}

// NewWorkflowStepStatesResponseWithDefaults instantiates a new WorkflowStepStatesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowStepStatesResponseWithDefaults() *WorkflowStepStatesResponse {
	this := WorkflowStepStatesResponse{}
	return &this
}

// GetSteps returns the Steps field value
func (o *WorkflowStepStatesResponse) GetSteps() []WorkflowStepState {
	if o == nil {
		var ret []WorkflowStepState
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *WorkflowStepStatesResponse) GetStepsOk() ([]WorkflowStepState, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *WorkflowStepStatesResponse) SetSteps(v []WorkflowStepState) {
	o.Steps = v
}

func (o WorkflowStepStatesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowStepStatesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["steps"] = o.Steps
	return toSerialize, nil
}

func (o *WorkflowStepStatesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"steps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowStepStatesResponse := _WorkflowStepStatesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowStepStatesResponse)

	if err != nil {
		return err
	}

	*o = WorkflowStepStatesResponse(varWorkflowStepStatesResponse)

	return err
}

type NullableWorkflowStepStatesResponse struct {
	value *WorkflowStepStatesResponse
	isSet bool
}

func (v NullableWorkflowStepStatesResponse) Get() *WorkflowStepStatesResponse {
	return v.value
}

func (v *NullableWorkflowStepStatesResponse) Set(val *WorkflowStepStatesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowStepStatesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowStepStatesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowStepStatesResponse(val *WorkflowStepStatesResponse) *NullableWorkflowStepStatesResponse {
	return &NullableWorkflowStepStatesResponse{value: val, isSet: true}
}

func (v NullableWorkflowStepStatesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowStepStatesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


