/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWorkflowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowResponse{}

// CreateWorkflowResponse struct for CreateWorkflowResponse
type CreateWorkflowResponse struct {
	WorkflowId string `json:"workflow_id"`
}

type _CreateWorkflowResponse CreateWorkflowResponse

// NewCreateWorkflowResponse instantiates a new CreateWorkflowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowResponse(workflowId string) *CreateWorkflowResponse {
	this := CreateWorkflowResponse{}
	this.WorkflowId = workflowId
	return &this
}

// NewCreateWorkflowResponseWithDefaults instantiates a new CreateWorkflowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowResponseWithDefaults() *CreateWorkflowResponse {
	this := CreateWorkflowResponse{}
	return &this
}

// GetWorkflowId returns the WorkflowId field value
func (o *CreateWorkflowResponse) GetWorkflowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowResponse) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *CreateWorkflowResponse) SetWorkflowId(v string) {
	o.WorkflowId = v
}

func (o CreateWorkflowResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workflow_id"] = o.WorkflowId
	return toSerialize, nil
}

func (o *CreateWorkflowResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workflow_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkflowResponse := _CreateWorkflowResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkflowResponse)

	if err != nil {
		return err
	}

	*o = CreateWorkflowResponse(varCreateWorkflowResponse)

	return err
}

type NullableCreateWorkflowResponse struct {
	value *CreateWorkflowResponse
	isSet bool
}

func (v NullableCreateWorkflowResponse) Get() *CreateWorkflowResponse {
	return v.value
}

func (v *NullableCreateWorkflowResponse) Set(val *CreateWorkflowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowResponse(val *CreateWorkflowResponse) *NullableCreateWorkflowResponse {
	return &NullableCreateWorkflowResponse{value: val, isSet: true}
}

func (v NullableCreateWorkflowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


