/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Job type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Job{}

// Job A single unit of work.
type Job struct {
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	Config JobConfig `json:"config"`
	CreatedAt time.Time `json:"created_at"`
	// How many times this job has been claimed (delivered to a worker). Greater than `retry_count + 1` means a lease expired without a report — i.e. a worker crashed mid-run.
	DeliveryCount *int32 `json:"delivery_count,omitempty"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	Id string `json:"id"`
	// Client-supplied key that makes job creation idempotent per tenant: re-submitting the same key returns the original job instead of creating a duplicate.
	IdempotencyKey NullableString `json:"idempotency_key,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// When this job's next retry becomes claimable (mirrors `scheduled_at` while the job is `retrying`; kept for audit/inspection).
	NextRetryAt NullableTime `json:"next_retry_at,omitempty"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	QueueName string `json:"queue_name"`
	Result map[string]interface{} `json:"result,omitempty"`
	RetryCount int32 `json:"retry_count"`
	// When the job becomes claimable. `created_at` for immediate jobs, the requested `run_at` for scheduled jobs, and the next backoff instant while retrying — the durable delay lives in the row itself.
	ScheduledAt time.Time `json:"scheduled_at"`
	StartedAt NullableTime `json:"started_at,omitempty"`
	Status JobStatus `json:"status"`
	TaskName string `json:"task_name"`
	TenantId NullableString `json:"tenant_id,omitempty"`
	WorkflowId NullableString `json:"workflow_id,omitempty"`
	// The owning workflow step's name (steps are addressed by name).
	WorkflowStepId NullableString `json:"workflow_step_id,omitempty"`
}

type _Job Job

// NewJob instantiates a new Job object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJob(config JobConfig, createdAt time.Time, id string, queueName string, retryCount int32, scheduledAt time.Time, status JobStatus, taskName string) *Job {
	this := Job{}
	this.Config = config
	this.CreatedAt = createdAt
	this.Id = id
	this.QueueName = queueName
	this.RetryCount = retryCount
	this.ScheduledAt = scheduledAt
	this.Status = status
	this.TaskName = taskName
	return &this
}

// NewJobWithDefaults instantiates a new Job object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobWithDefaults() *Job {
	this := Job{}
	return &this
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *Job) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *Job) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *Job) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *Job) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetConfig returns the Config field value
func (o *Job) GetConfig() JobConfig {
	if o == nil {
		var ret JobConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *Job) GetConfigOk() (*JobConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *Job) SetConfig(v JobConfig) {
	o.Config = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Job) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Job) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Job) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDeliveryCount returns the DeliveryCount field value if set, zero value otherwise.
func (o *Job) GetDeliveryCount() int32 {
	if o == nil || IsNil(o.DeliveryCount) {
		var ret int32
		return ret
	}
	return *o.DeliveryCount
}

// GetDeliveryCountOk returns a tuple with the DeliveryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetDeliveryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DeliveryCount) {
		return nil, false
	}
	return o.DeliveryCount, true
}

// HasDeliveryCount returns a boolean if a field has been set.
func (o *Job) HasDeliveryCount() bool {
	if o != nil && !IsNil(o.DeliveryCount) {
		return true
	}

	return false
}

// SetDeliveryCount gets a reference to the given int32 and assigns it to the DeliveryCount field.
func (o *Job) SetDeliveryCount(v int32) {
	o.DeliveryCount = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *Job) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *Job) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *Job) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *Job) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetId returns the Id field value
func (o *Job) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Job) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Job) SetId(v string) {
	o.Id = v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey.Get()) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey.Get()
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IdempotencyKey.Get(), o.IdempotencyKey.IsSet()
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *Job) HasIdempotencyKey() bool {
	if o != nil && o.IdempotencyKey.IsSet() {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given NullableString and assigns it to the IdempotencyKey field.
func (o *Job) SetIdempotencyKey(v string) {
	o.IdempotencyKey.Set(&v)
}
// SetIdempotencyKeyNil sets the value for IdempotencyKey to be an explicit nil
func (o *Job) SetIdempotencyKeyNil() {
	o.IdempotencyKey.Set(nil)
}

// UnsetIdempotencyKey ensures that no value is present for IdempotencyKey, not even an explicit nil
func (o *Job) UnsetIdempotencyKey() {
	o.IdempotencyKey.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Job) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Job) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *Job) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetNextRetryAt returns the NextRetryAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetNextRetryAt() time.Time {
	if o == nil || IsNil(o.NextRetryAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.NextRetryAt.Get()
}

// GetNextRetryAtOk returns a tuple with the NextRetryAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetNextRetryAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextRetryAt.Get(), o.NextRetryAt.IsSet()
}

// HasNextRetryAt returns a boolean if a field has been set.
func (o *Job) HasNextRetryAt() bool {
	if o != nil && o.NextRetryAt.IsSet() {
		return true
	}

	return false
}

// SetNextRetryAt gets a reference to the given NullableTime and assigns it to the NextRetryAt field.
func (o *Job) SetNextRetryAt(v time.Time) {
	o.NextRetryAt.Set(&v)
}
// SetNextRetryAtNil sets the value for NextRetryAt to be an explicit nil
func (o *Job) SetNextRetryAtNil() {
	o.NextRetryAt.Set(nil)
}

// UnsetNextRetryAt ensures that no value is present for NextRetryAt, not even an explicit nil
func (o *Job) UnsetNextRetryAt() {
	o.NextRetryAt.Unset()
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *Job) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *Job) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *Job) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetQueueName returns the QueueName field value
func (o *Job) GetQueueName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueueName
}

// GetQueueNameOk returns a tuple with the QueueName field value
// and a boolean to check if the value has been set.
func (o *Job) GetQueueNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueueName, true
}

// SetQueueName sets field value
func (o *Job) SetQueueName(v string) {
	o.QueueName = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *Job) GetResult() map[string]interface{} {
	if o == nil || IsNil(o.Result) {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *Job) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *Job) SetResult(v map[string]interface{}) {
	o.Result = v
}

// GetRetryCount returns the RetryCount field value
func (o *Job) GetRetryCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetryCount
}

// GetRetryCountOk returns a tuple with the RetryCount field value
// and a boolean to check if the value has been set.
func (o *Job) GetRetryCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetryCount, true
}

// SetRetryCount sets field value
func (o *Job) SetRetryCount(v int32) {
	o.RetryCount = v
}

// GetScheduledAt returns the ScheduledAt field value
func (o *Job) GetScheduledAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ScheduledAt
}

// GetScheduledAtOk returns a tuple with the ScheduledAt field value
// and a boolean to check if the value has been set.
func (o *Job) GetScheduledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledAt, true
}

// SetScheduledAt sets field value
func (o *Job) SetScheduledAt(v time.Time) {
	o.ScheduledAt = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *Job) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *Job) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *Job) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *Job) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetStatus returns the Status field value
func (o *Job) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Job) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Job) SetStatus(v JobStatus) {
	o.Status = v
}

// GetTaskName returns the TaskName field value
func (o *Job) GetTaskName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value
// and a boolean to check if the value has been set.
func (o *Job) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskName, true
}

// SetTaskName sets field value
func (o *Job) SetTaskName(v string) {
	o.TaskName = v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *Job) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *Job) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *Job) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *Job) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkflowId.Get()
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowId.Get(), o.WorkflowId.IsSet()
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *Job) HasWorkflowId() bool {
	if o != nil && o.WorkflowId.IsSet() {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given NullableString and assigns it to the WorkflowId field.
func (o *Job) SetWorkflowId(v string) {
	o.WorkflowId.Set(&v)
}
// SetWorkflowIdNil sets the value for WorkflowId to be an explicit nil
func (o *Job) SetWorkflowIdNil() {
	o.WorkflowId.Set(nil)
}

// UnsetWorkflowId ensures that no value is present for WorkflowId, not even an explicit nil
func (o *Job) UnsetWorkflowId() {
	o.WorkflowId.Unset()
}

// GetWorkflowStepId returns the WorkflowStepId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Job) GetWorkflowStepId() string {
	if o == nil || IsNil(o.WorkflowStepId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkflowStepId.Get()
}

// GetWorkflowStepIdOk returns a tuple with the WorkflowStepId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Job) GetWorkflowStepIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowStepId.Get(), o.WorkflowStepId.IsSet()
}

// HasWorkflowStepId returns a boolean if a field has been set.
func (o *Job) HasWorkflowStepId() bool {
	if o != nil && o.WorkflowStepId.IsSet() {
		return true
	}

	return false
}

// SetWorkflowStepId gets a reference to the given NullableString and assigns it to the WorkflowStepId field.
func (o *Job) SetWorkflowStepId(v string) {
	o.WorkflowStepId.Set(&v)
}
// SetWorkflowStepIdNil sets the value for WorkflowStepId to be an explicit nil
func (o *Job) SetWorkflowStepIdNil() {
	o.WorkflowStepId.Set(nil)
}

// UnsetWorkflowStepId ensures that no value is present for WorkflowStepId, not even an explicit nil
func (o *Job) UnsetWorkflowStepId() {
	o.WorkflowStepId.Unset()
}

func (o Job) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Job) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	toSerialize["config"] = o.Config
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.DeliveryCount) {
		toSerialize["delivery_count"] = o.DeliveryCount
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	toSerialize["id"] = o.Id
	if o.IdempotencyKey.IsSet() {
		toSerialize["idempotency_key"] = o.IdempotencyKey.Get()
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.NextRetryAt.IsSet() {
		toSerialize["next_retry_at"] = o.NextRetryAt.Get()
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	toSerialize["queue_name"] = o.QueueName
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	toSerialize["retry_count"] = o.RetryCount
	toSerialize["scheduled_at"] = o.ScheduledAt
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["task_name"] = o.TaskName
	if o.TenantId.IsSet() {
		toSerialize["tenant_id"] = o.TenantId.Get()
	}
	if o.WorkflowId.IsSet() {
		toSerialize["workflow_id"] = o.WorkflowId.Get()
	}
	if o.WorkflowStepId.IsSet() {
		toSerialize["workflow_step_id"] = o.WorkflowStepId.Get()
	}
	return toSerialize, nil
}

func (o *Job) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
		"created_at",
		"id",
		"queue_name",
		"retry_count",
		"scheduled_at",
		"status",
		"task_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJob := _Job{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJob)

	if err != nil {
		return err
	}

	*o = Job(varJob)

	return err
}

type NullableJob struct {
	value *Job
	isSet bool
}

func (v NullableJob) Get() *Job {
	return v.value
}

func (v *NullableJob) Set(val *Job) {
	v.value = val
	v.isSet = true
}

func (v NullableJob) IsSet() bool {
	return v.isSet
}

func (v *NullableJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJob(val *Job) *NullableJob {
	return &NullableJob{value: val, isSet: true}
}

func (v NullableJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


