/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HeartbeatResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeartbeatResponse{}

// HeartbeatResponse Response for `POST /api/v1/jobs/{id}/heartbeat`.
type HeartbeatResponse struct {
	// The job's current status. `running` means the lease was extended; anything else (`cancelled`, `completed`, ...) means it was not, and the worker should stop working on the job.
	Status JobStatus `json:"status"`
}

type _HeartbeatResponse HeartbeatResponse

// NewHeartbeatResponse instantiates a new HeartbeatResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeartbeatResponse(status JobStatus) *HeartbeatResponse {
	this := HeartbeatResponse{}
	this.Status = status
	return &this
}

// NewHeartbeatResponseWithDefaults instantiates a new HeartbeatResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeartbeatResponseWithDefaults() *HeartbeatResponse {
	this := HeartbeatResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *HeartbeatResponse) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HeartbeatResponse) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HeartbeatResponse) SetStatus(v JobStatus) {
	o.Status = v
}

func (o HeartbeatResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeartbeatResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *HeartbeatResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHeartbeatResponse := _HeartbeatResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHeartbeatResponse)

	if err != nil {
		return err
	}

	*o = HeartbeatResponse(varHeartbeatResponse)

	return err
}

type NullableHeartbeatResponse struct {
	value *HeartbeatResponse
	isSet bool
}

func (v NullableHeartbeatResponse) Get() *HeartbeatResponse {
	return v.value
}

func (v *NullableHeartbeatResponse) Set(val *HeartbeatResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHeartbeatResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHeartbeatResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeartbeatResponse(val *HeartbeatResponse) *NullableHeartbeatResponse {
	return &NullableHeartbeatResponse{value: val, isSet: true}
}

func (v NullableHeartbeatResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeartbeatResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


