/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
)

// checks if the LeaseJobsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeaseJobsRequest{}

// LeaseJobsRequest Body for `POST /api/v1/queues/{queue}/lease`.
type LeaseJobsRequest struct {
	// Lease duration in seconds (1..=3600, default 30). Heartbeat to extend.
	LeaseSecs NullableInt32 `json:"lease_secs,omitempty"`
	// Maximum jobs to lease in one call (1..=100, default 1).
	MaxJobs NullableInt32 `json:"max_jobs,omitempty"`
	// Long-poll wait when the queue is empty, in seconds (0..=30, default 0).
	WaitSecs NullableInt32 `json:"wait_secs,omitempty"`
}

// NewLeaseJobsRequest instantiates a new LeaseJobsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaseJobsRequest() *LeaseJobsRequest {
	this := LeaseJobsRequest{}
	return &this
}

// NewLeaseJobsRequestWithDefaults instantiates a new LeaseJobsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaseJobsRequestWithDefaults() *LeaseJobsRequest {
	this := LeaseJobsRequest{}
	return &this
}

// GetLeaseSecs returns the LeaseSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LeaseJobsRequest) GetLeaseSecs() int32 {
	if o == nil || IsNil(o.LeaseSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.LeaseSecs.Get()
}

// GetLeaseSecsOk returns a tuple with the LeaseSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LeaseJobsRequest) GetLeaseSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LeaseSecs.Get(), o.LeaseSecs.IsSet()
}

// HasLeaseSecs returns a boolean if a field has been set.
func (o *LeaseJobsRequest) HasLeaseSecs() bool {
	if o != nil && o.LeaseSecs.IsSet() {
		return true
	}

	return false
}

// SetLeaseSecs gets a reference to the given NullableInt32 and assigns it to the LeaseSecs field.
func (o *LeaseJobsRequest) SetLeaseSecs(v int32) {
	o.LeaseSecs.Set(&v)
}
// SetLeaseSecsNil sets the value for LeaseSecs to be an explicit nil
func (o *LeaseJobsRequest) SetLeaseSecsNil() {
	o.LeaseSecs.Set(nil)
}

// UnsetLeaseSecs ensures that no value is present for LeaseSecs, not even an explicit nil
func (o *LeaseJobsRequest) UnsetLeaseSecs() {
	o.LeaseSecs.Unset()
}

// GetMaxJobs returns the MaxJobs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LeaseJobsRequest) GetMaxJobs() int32 {
	if o == nil || IsNil(o.MaxJobs.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxJobs.Get()
}

// GetMaxJobsOk returns a tuple with the MaxJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LeaseJobsRequest) GetMaxJobsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxJobs.Get(), o.MaxJobs.IsSet()
}

// HasMaxJobs returns a boolean if a field has been set.
func (o *LeaseJobsRequest) HasMaxJobs() bool {
	if o != nil && o.MaxJobs.IsSet() {
		return true
	}

	return false
}

// SetMaxJobs gets a reference to the given NullableInt32 and assigns it to the MaxJobs field.
func (o *LeaseJobsRequest) SetMaxJobs(v int32) {
	o.MaxJobs.Set(&v)
}
// SetMaxJobsNil sets the value for MaxJobs to be an explicit nil
func (o *LeaseJobsRequest) SetMaxJobsNil() {
	o.MaxJobs.Set(nil)
}

// UnsetMaxJobs ensures that no value is present for MaxJobs, not even an explicit nil
func (o *LeaseJobsRequest) UnsetMaxJobs() {
	o.MaxJobs.Unset()
}

// GetWaitSecs returns the WaitSecs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LeaseJobsRequest) GetWaitSecs() int32 {
	if o == nil || IsNil(o.WaitSecs.Get()) {
		var ret int32
		return ret
	}
	return *o.WaitSecs.Get()
}

// GetWaitSecsOk returns a tuple with the WaitSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LeaseJobsRequest) GetWaitSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WaitSecs.Get(), o.WaitSecs.IsSet()
}

// HasWaitSecs returns a boolean if a field has been set.
func (o *LeaseJobsRequest) HasWaitSecs() bool {
	if o != nil && o.WaitSecs.IsSet() {
		return true
	}

	return false
}

// SetWaitSecs gets a reference to the given NullableInt32 and assigns it to the WaitSecs field.
func (o *LeaseJobsRequest) SetWaitSecs(v int32) {
	o.WaitSecs.Set(&v)
}
// SetWaitSecsNil sets the value for WaitSecs to be an explicit nil
func (o *LeaseJobsRequest) SetWaitSecsNil() {
	o.WaitSecs.Set(nil)
}

// UnsetWaitSecs ensures that no value is present for WaitSecs, not even an explicit nil
func (o *LeaseJobsRequest) UnsetWaitSecs() {
	o.WaitSecs.Unset()
}

func (o LeaseJobsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeaseJobsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.LeaseSecs.IsSet() {
		toSerialize["lease_secs"] = o.LeaseSecs.Get()
	}
	if o.MaxJobs.IsSet() {
		toSerialize["max_jobs"] = o.MaxJobs.Get()
	}
	if o.WaitSecs.IsSet() {
		toSerialize["wait_secs"] = o.WaitSecs.Get()
	}
	return toSerialize, nil
}

type NullableLeaseJobsRequest struct {
	value *LeaseJobsRequest
	isSet bool
}

func (v NullableLeaseJobsRequest) Get() *LeaseJobsRequest {
	return v.value
}

func (v *NullableLeaseJobsRequest) Set(val *LeaseJobsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaseJobsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaseJobsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaseJobsRequest(val *LeaseJobsRequest) *NullableLeaseJobsRequest {
	return &NullableLeaseJobsRequest{value: val, isSet: true}
}

func (v NullableLeaseJobsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaseJobsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


