/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeasedJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeasedJob{}

// LeasedJob A job leased to a (possibly remote) worker, together with the lease token needed to heartbeat, complete, or fail it.
type LeasedJob struct {
	Job Job `json:"job"`
	// Opaque, unguessable proof of lease ownership, regenerated on every claim. Pass it back on heartbeat/complete/fail; a stale token (the lease expired and the job was reclaimed) is rejected.
	LeaseToken string `json:"lease_token"`
}

type _LeasedJob LeasedJob

// NewLeasedJob instantiates a new LeasedJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeasedJob(job Job, leaseToken string) *LeasedJob {
	this := LeasedJob{}
	this.Job = job
	this.LeaseToken = leaseToken
	return &this
}

// NewLeasedJobWithDefaults instantiates a new LeasedJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeasedJobWithDefaults() *LeasedJob {
	this := LeasedJob{}
	return &this
}

// GetJob returns the Job field value
func (o *LeasedJob) GetJob() Job {
	if o == nil {
		var ret Job
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *LeasedJob) GetJobOk() (*Job, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *LeasedJob) SetJob(v Job) {
	o.Job = v
}

// GetLeaseToken returns the LeaseToken field value
func (o *LeasedJob) GetLeaseToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaseToken
}

// GetLeaseTokenOk returns a tuple with the LeaseToken field value
// and a boolean to check if the value has been set.
func (o *LeasedJob) GetLeaseTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaseToken, true
}

// SetLeaseToken sets field value
func (o *LeasedJob) SetLeaseToken(v string) {
	o.LeaseToken = v
}

func (o LeasedJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeasedJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job"] = o.Job
	toSerialize["lease_token"] = o.LeaseToken
	return toSerialize, nil
}

func (o *LeasedJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job",
		"lease_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeasedJob := _LeasedJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeasedJob)

	if err != nil {
		return err
	}

	*o = LeasedJob(varLeasedJob)

	return err
}

type NullableLeasedJob struct {
	value *LeasedJob
	isSet bool
}

func (v NullableLeasedJob) Get() *LeasedJob {
	return v.value
}

func (v *NullableLeasedJob) Set(val *LeasedJob) {
	v.value = val
	v.isSet = true
}

func (v NullableLeasedJob) IsSet() bool {
	return v.isSet
}

func (v *NullableLeasedJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeasedJob(val *LeasedJob) *NullableLeasedJob {
	return &NullableLeasedJob{value: val, isSet: true}
}

func (v NullableLeasedJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeasedJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


