/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"fmt"
)

// BackoffStrategy How retry delays grow between attempts.
type BackoffStrategy string

// List of BackoffStrategy
const (
	BACKOFFSTRATEGY_FIXED BackoffStrategy = "fixed"
	BACKOFFSTRATEGY_LINEAR BackoffStrategy = "linear"
	BACKOFFSTRATEGY_EXPONENTIAL BackoffStrategy = "exponential"
)

// All allowed values of BackoffStrategy enum
var AllowedBackoffStrategyEnumValues = []BackoffStrategy{
	"fixed",
	"linear",
	"exponential",
}

func (v *BackoffStrategy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BackoffStrategy(value)
	for _, existing := range AllowedBackoffStrategyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BackoffStrategy", value)
}

// NewBackoffStrategyFromValue returns a pointer to a valid BackoffStrategy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBackoffStrategyFromValue(v string) (*BackoffStrategy, error) {
	ev := BackoffStrategy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BackoffStrategy: valid values are %v", v, AllowedBackoffStrategyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BackoffStrategy) IsValid() bool {
	for _, existing := range AllowedBackoffStrategyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BackoffStrategy value
func (v BackoffStrategy) Ptr() *BackoffStrategy {
	return &v
}

type NullableBackoffStrategy struct {
	value *BackoffStrategy
	isSet bool
}

func (v NullableBackoffStrategy) Get() *BackoffStrategy {
	return v.value
}

func (v *NullableBackoffStrategy) Set(val *BackoffStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableBackoffStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableBackoffStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackoffStrategy(val *BackoffStrategy) *NullableBackoffStrategy {
	return &NullableBackoffStrategy{value: val, isSet: true}
}

func (v NullableBackoffStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackoffStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

