/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowDiagramResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowDiagramResponse{}

// WorkflowDiagramResponse struct for WorkflowDiagramResponse
type WorkflowDiagramResponse struct {
	// The diagram document (Mermaid `graph TD`).
	Diagram string `json:"diagram"`
	// Diagram source format. Always `mermaid` today.
	Format string `json:"format"`
}

type _WorkflowDiagramResponse WorkflowDiagramResponse

// NewWorkflowDiagramResponse instantiates a new WorkflowDiagramResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowDiagramResponse(diagram string, format string) *WorkflowDiagramResponse {
	this := WorkflowDiagramResponse{}
	this.Diagram = diagram
	this.Format = format
	return &this
}

// NewWorkflowDiagramResponseWithDefaults instantiates a new WorkflowDiagramResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowDiagramResponseWithDefaults() *WorkflowDiagramResponse {
	this := WorkflowDiagramResponse{}
	return &this
}

// GetDiagram returns the Diagram field value
func (o *WorkflowDiagramResponse) GetDiagram() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Diagram
}

// GetDiagramOk returns a tuple with the Diagram field value
// and a boolean to check if the value has been set.
func (o *WorkflowDiagramResponse) GetDiagramOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Diagram, true
}

// SetDiagram sets field value
func (o *WorkflowDiagramResponse) SetDiagram(v string) {
	o.Diagram = v
}

// GetFormat returns the Format field value
func (o *WorkflowDiagramResponse) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *WorkflowDiagramResponse) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *WorkflowDiagramResponse) SetFormat(v string) {
	o.Format = v
}

func (o WorkflowDiagramResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowDiagramResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["diagram"] = o.Diagram
	toSerialize["format"] = o.Format
	return toSerialize, nil
}

func (o *WorkflowDiagramResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"diagram",
		"format",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowDiagramResponse := _WorkflowDiagramResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowDiagramResponse)

	if err != nil {
		return err
	}

	*o = WorkflowDiagramResponse(varWorkflowDiagramResponse)

	return err
}

type NullableWorkflowDiagramResponse struct {
	value *WorkflowDiagramResponse
	isSet bool
}

func (v NullableWorkflowDiagramResponse) Get() *WorkflowDiagramResponse {
	return v.value
}

func (v *NullableWorkflowDiagramResponse) Set(val *WorkflowDiagramResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowDiagramResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowDiagramResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowDiagramResponse(val *WorkflowDiagramResponse) *NullableWorkflowDiagramResponse {
	return &NullableWorkflowDiagramResponse{value: val, isSet: true}
}

func (v NullableWorkflowDiagramResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowDiagramResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


