/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"fmt"
)

// OnFailure What to do with downstream steps when a step fails.
type OnFailure string

// List of OnFailure
const (
	ONFAILURE_HALT OnFailure = "halt"
	ONFAILURE_SKIP OnFailure = "skip"
	ONFAILURE_CONTINUE OnFailure = "continue"
)

// All allowed values of OnFailure enum
var AllowedOnFailureEnumValues = []OnFailure{
	"halt",
	"skip",
	"continue",
}

func (v *OnFailure) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OnFailure(value)
	for _, existing := range AllowedOnFailureEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OnFailure", value)
}

// NewOnFailureFromValue returns a pointer to a valid OnFailure
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOnFailureFromValue(v string) (*OnFailure, error) {
	ev := OnFailure(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OnFailure: valid values are %v", v, AllowedOnFailureEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OnFailure) IsValid() bool {
	for _, existing := range AllowedOnFailureEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OnFailure value
func (v OnFailure) Ptr() *OnFailure {
	return &v
}

type NullableOnFailure struct {
	value *OnFailure
	isSet bool
}

func (v NullableOnFailure) Get() *OnFailure {
	return v.value
}

func (v *NullableOnFailure) Set(val *OnFailure) {
	v.value = val
	v.isSet = true
}

func (v NullableOnFailure) IsSet() bool {
	return v.isSet
}

func (v *NullableOnFailure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnFailure(val *OnFailure) *NullableOnFailure {
	return &NullableOnFailure{value: val, isSet: true}
}

func (v NullableOnFailure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnFailure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

