/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompleteJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompleteJobRequest{}

// CompleteJobRequest Body for `POST /api/v1/jobs/{id}/complete`.
type CompleteJobRequest struct {
	// The lease token returned by the lease call.
	LeaseToken string `json:"lease_token"`
	// Handler result, recorded on the job and merged into workflow context.
	Result map[string]interface{} `json:"result,omitempty"`
}

type _CompleteJobRequest CompleteJobRequest

// NewCompleteJobRequest instantiates a new CompleteJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompleteJobRequest(leaseToken string) *CompleteJobRequest {
	this := CompleteJobRequest{}
	this.LeaseToken = leaseToken
	return &this
}

// NewCompleteJobRequestWithDefaults instantiates a new CompleteJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompleteJobRequestWithDefaults() *CompleteJobRequest {
	this := CompleteJobRequest{}
	return &this
}

// GetLeaseToken returns the LeaseToken field value
func (o *CompleteJobRequest) GetLeaseToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaseToken
}

// GetLeaseTokenOk returns a tuple with the LeaseToken field value
// and a boolean to check if the value has been set.
func (o *CompleteJobRequest) GetLeaseTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaseToken, true
}

// SetLeaseToken sets field value
func (o *CompleteJobRequest) SetLeaseToken(v string) {
	o.LeaseToken = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CompleteJobRequest) GetResult() map[string]interface{} {
	if o == nil || IsNil(o.Result) {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompleteJobRequest) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CompleteJobRequest) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *CompleteJobRequest) SetResult(v map[string]interface{}) {
	o.Result = v
}

func (o CompleteJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompleteJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lease_token"] = o.LeaseToken
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *CompleteJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lease_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompleteJobRequest := _CompleteJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompleteJobRequest)

	if err != nil {
		return err
	}

	*o = CompleteJobRequest(varCompleteJobRequest)

	return err
}

type NullableCompleteJobRequest struct {
	value *CompleteJobRequest
	isSet bool
}

func (v NullableCompleteJobRequest) Get() *CompleteJobRequest {
	return v.value
}

func (v *NullableCompleteJobRequest) Set(val *CompleteJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompleteJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompleteJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompleteJobRequest(val *CompleteJobRequest) *NullableCompleteJobRequest {
	return &NullableCompleteJobRequest{value: val, isSet: true}
}

func (v NullableCompleteJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompleteJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


