/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CronSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CronSchedule{}

// CronSchedule A recurring enqueue schedule. Expressions are standard 5-field crontab (`minute hour day-of-month month day-of-week`), evaluated in **UTC**; a 6/7-field form with leading seconds is also accepted.
type CronSchedule struct {
	Config NullableJobConfig `json:"config,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	CronExpr string `json:"cron_expr"`
	Enabled bool `json:"enabled"`
	Id string `json:"id"`
	LastEnqueuedAt NullableTime `json:"last_enqueued_at,omitempty"`
	// Unique per tenant.
	Name string `json:"name"`
	// The next instant this schedule fires. Missed occurrences (server down) collapse into at most one catch-up firing.
	NextRunAt time.Time `json:"next_run_at"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Queue for the enqueued jobs (the engine default when absent).
	QueueName NullableString `json:"queue_name,omitempty"`
	TaskName string `json:"task_name"`
	TenantId NullableString `json:"tenant_id,omitempty"`
}

type _CronSchedule CronSchedule

// NewCronSchedule instantiates a new CronSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCronSchedule(createdAt time.Time, cronExpr string, enabled bool, id string, name string, nextRunAt time.Time, taskName string) *CronSchedule {
	this := CronSchedule{}
	this.CreatedAt = createdAt
	this.CronExpr = cronExpr
	this.Enabled = enabled
	this.Id = id
	this.Name = name
	this.NextRunAt = nextRunAt
	this.TaskName = taskName
	return &this
}

// NewCronScheduleWithDefaults instantiates a new CronSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCronScheduleWithDefaults() *CronSchedule {
	this := CronSchedule{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CronSchedule) GetConfig() JobConfig {
	if o == nil || IsNil(o.Config.Get()) {
		var ret JobConfig
		return ret
	}
	return *o.Config.Get()
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CronSchedule) GetConfigOk() (*JobConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Config.Get(), o.Config.IsSet()
}

// HasConfig returns a boolean if a field has been set.
func (o *CronSchedule) HasConfig() bool {
	if o != nil && o.Config.IsSet() {
		return true
	}

	return false
}

// SetConfig gets a reference to the given NullableJobConfig and assigns it to the Config field.
func (o *CronSchedule) SetConfig(v JobConfig) {
	o.Config.Set(&v)
}
// SetConfigNil sets the value for Config to be an explicit nil
func (o *CronSchedule) SetConfigNil() {
	o.Config.Set(nil)
}

// UnsetConfig ensures that no value is present for Config, not even an explicit nil
func (o *CronSchedule) UnsetConfig() {
	o.Config.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *CronSchedule) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CronSchedule) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCronExpr returns the CronExpr field value
func (o *CronSchedule) GetCronExpr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CronExpr
}

// GetCronExprOk returns a tuple with the CronExpr field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetCronExprOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CronExpr, true
}

// SetCronExpr sets field value
func (o *CronSchedule) SetCronExpr(v string) {
	o.CronExpr = v
}

// GetEnabled returns the Enabled field value
func (o *CronSchedule) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CronSchedule) SetEnabled(v bool) {
	o.Enabled = v
}

// GetId returns the Id field value
func (o *CronSchedule) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CronSchedule) SetId(v string) {
	o.Id = v
}

// GetLastEnqueuedAt returns the LastEnqueuedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CronSchedule) GetLastEnqueuedAt() time.Time {
	if o == nil || IsNil(o.LastEnqueuedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastEnqueuedAt.Get()
}

// GetLastEnqueuedAtOk returns a tuple with the LastEnqueuedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CronSchedule) GetLastEnqueuedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastEnqueuedAt.Get(), o.LastEnqueuedAt.IsSet()
}

// HasLastEnqueuedAt returns a boolean if a field has been set.
func (o *CronSchedule) HasLastEnqueuedAt() bool {
	if o != nil && o.LastEnqueuedAt.IsSet() {
		return true
	}

	return false
}

// SetLastEnqueuedAt gets a reference to the given NullableTime and assigns it to the LastEnqueuedAt field.
func (o *CronSchedule) SetLastEnqueuedAt(v time.Time) {
	o.LastEnqueuedAt.Set(&v)
}
// SetLastEnqueuedAtNil sets the value for LastEnqueuedAt to be an explicit nil
func (o *CronSchedule) SetLastEnqueuedAtNil() {
	o.LastEnqueuedAt.Set(nil)
}

// UnsetLastEnqueuedAt ensures that no value is present for LastEnqueuedAt, not even an explicit nil
func (o *CronSchedule) UnsetLastEnqueuedAt() {
	o.LastEnqueuedAt.Unset()
}

// GetName returns the Name field value
func (o *CronSchedule) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CronSchedule) SetName(v string) {
	o.Name = v
}

// GetNextRunAt returns the NextRunAt field value
func (o *CronSchedule) GetNextRunAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.NextRunAt
}

// GetNextRunAtOk returns a tuple with the NextRunAt field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetNextRunAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextRunAt, true
}

// SetNextRunAt sets field value
func (o *CronSchedule) SetNextRunAt(v time.Time) {
	o.NextRunAt = v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *CronSchedule) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *CronSchedule) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *CronSchedule) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetQueueName returns the QueueName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CronSchedule) GetQueueName() string {
	if o == nil || IsNil(o.QueueName.Get()) {
		var ret string
		return ret
	}
	return *o.QueueName.Get()
}

// GetQueueNameOk returns a tuple with the QueueName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CronSchedule) GetQueueNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueueName.Get(), o.QueueName.IsSet()
}

// HasQueueName returns a boolean if a field has been set.
func (o *CronSchedule) HasQueueName() bool {
	if o != nil && o.QueueName.IsSet() {
		return true
	}

	return false
}

// SetQueueName gets a reference to the given NullableString and assigns it to the QueueName field.
func (o *CronSchedule) SetQueueName(v string) {
	o.QueueName.Set(&v)
}
// SetQueueNameNil sets the value for QueueName to be an explicit nil
func (o *CronSchedule) SetQueueNameNil() {
	o.QueueName.Set(nil)
}

// UnsetQueueName ensures that no value is present for QueueName, not even an explicit nil
func (o *CronSchedule) UnsetQueueName() {
	o.QueueName.Unset()
}

// GetTaskName returns the TaskName field value
func (o *CronSchedule) GetTaskName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value
// and a boolean to check if the value has been set.
func (o *CronSchedule) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskName, true
}

// SetTaskName sets field value
func (o *CronSchedule) SetTaskName(v string) {
	o.TaskName = v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CronSchedule) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CronSchedule) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *CronSchedule) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *CronSchedule) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *CronSchedule) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *CronSchedule) UnsetTenantId() {
	o.TenantId.Unset()
}

func (o CronSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CronSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config.IsSet() {
		toSerialize["config"] = o.Config.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["cron_expr"] = o.CronExpr
	toSerialize["enabled"] = o.Enabled
	toSerialize["id"] = o.Id
	if o.LastEnqueuedAt.IsSet() {
		toSerialize["last_enqueued_at"] = o.LastEnqueuedAt.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["next_run_at"] = o.NextRunAt
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if o.QueueName.IsSet() {
		toSerialize["queue_name"] = o.QueueName.Get()
	}
	toSerialize["task_name"] = o.TaskName
	if o.TenantId.IsSet() {
		toSerialize["tenant_id"] = o.TenantId.Get()
	}
	return toSerialize, nil
}

func (o *CronSchedule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"cron_expr",
		"enabled",
		"id",
		"name",
		"next_run_at",
		"task_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCronSchedule := _CronSchedule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCronSchedule)

	if err != nil {
		return err
	}

	*o = CronSchedule(varCronSchedule)

	return err
}

type NullableCronSchedule struct {
	value *CronSchedule
	isSet bool
}

func (v NullableCronSchedule) Get() *CronSchedule {
	return v.value
}

func (v *NullableCronSchedule) Set(val *CronSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableCronSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableCronSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCronSchedule(val *CronSchedule) *NullableCronSchedule {
	return &NullableCronSchedule{value: val, isSet: true}
}

func (v NullableCronSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCronSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


