/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateJobResponse{}

// CreateJobResponse struct for CreateJobResponse
type CreateJobResponse struct {
	JobId string `json:"job_id"`
}

type _CreateJobResponse CreateJobResponse

// NewCreateJobResponse instantiates a new CreateJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateJobResponse(jobId string) *CreateJobResponse {
	this := CreateJobResponse{}
	this.JobId = jobId
	return &this
}

// NewCreateJobResponseWithDefaults instantiates a new CreateJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateJobResponseWithDefaults() *CreateJobResponse {
	this := CreateJobResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *CreateJobResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *CreateJobResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *CreateJobResponse) SetJobId(v string) {
	o.JobId = v
}

func (o CreateJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	return toSerialize, nil
}

func (o *CreateJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateJobResponse := _CreateJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateJobResponse)

	if err != nil {
		return err
	}

	*o = CreateJobResponse(varCreateJobResponse)

	return err
}

type NullableCreateJobResponse struct {
	value *CreateJobResponse
	isSet bool
}

func (v NullableCreateJobResponse) Get() *CreateJobResponse {
	return v.value
}

func (v *NullableCreateJobResponse) Set(val *CreateJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateJobResponse(val *CreateJobResponse) *NullableCreateJobResponse {
	return &NullableCreateJobResponse{value: val, isSet: true}
}

func (v NullableCreateJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


