/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCronResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCronResponse{}

// CreateCronResponse struct for CreateCronResponse
type CreateCronResponse struct {
	CronId string `json:"cron_id"`
}

type _CreateCronResponse CreateCronResponse

// NewCreateCronResponse instantiates a new CreateCronResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCronResponse(cronId string) *CreateCronResponse {
	this := CreateCronResponse{}
	this.CronId = cronId
	return &this
}

// NewCreateCronResponseWithDefaults instantiates a new CreateCronResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCronResponseWithDefaults() *CreateCronResponse {
	this := CreateCronResponse{}
	return &this
}

// GetCronId returns the CronId field value
func (o *CreateCronResponse) GetCronId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CronId
}

// GetCronIdOk returns a tuple with the CronId field value
// and a boolean to check if the value has been set.
func (o *CreateCronResponse) GetCronIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CronId, true
}

// SetCronId sets field value
func (o *CreateCronResponse) SetCronId(v string) {
	o.CronId = v
}

func (o CreateCronResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCronResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cron_id"] = o.CronId
	return toSerialize, nil
}

func (o *CreateCronResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cron_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCronResponse := _CreateCronResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCronResponse)

	if err != nil {
		return err
	}

	*o = CreateCronResponse(varCreateCronResponse)

	return err
}

type NullableCreateCronResponse struct {
	value *CreateCronResponse
	isSet bool
}

func (v NullableCreateCronResponse) Get() *CreateCronResponse {
	return v.value
}

func (v *NullableCreateCronResponse) Set(val *CreateCronResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCronResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCronResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCronResponse(val *CreateCronResponse) *NullableCreateCronResponse {
	return &NullableCreateCronResponse{value: val, isSet: true}
}

func (v NullableCreateCronResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCronResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


