/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TasksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasksResponse{}

// TasksResponse struct for TasksResponse
type TasksResponse struct {
	Tasks []string `json:"tasks"`
}

type _TasksResponse TasksResponse

// NewTasksResponse instantiates a new TasksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasksResponse(tasks []string) *TasksResponse {
	this := TasksResponse{}
	this.Tasks = tasks
	return &this
}

// NewTasksResponseWithDefaults instantiates a new TasksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasksResponseWithDefaults() *TasksResponse {
	this := TasksResponse{}
	return &this
}

// GetTasks returns the Tasks field value
func (o *TasksResponse) GetTasks() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value
// and a boolean to check if the value has been set.
func (o *TasksResponse) GetTasksOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tasks, true
}

// SetTasks sets field value
func (o *TasksResponse) SetTasks(v []string) {
	o.Tasks = v
}

func (o TasksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tasks"] = o.Tasks
	return toSerialize, nil
}

func (o *TasksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tasks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTasksResponse := _TasksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTasksResponse)

	if err != nil {
		return err
	}

	*o = TasksResponse(varTasksResponse)

	return err
}

type NullableTasksResponse struct {
	value *TasksResponse
	isSet bool
}

func (v NullableTasksResponse) Get() *TasksResponse {
	return v.value
}

func (v *NullableTasksResponse) Set(val *TasksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksResponse(val *TasksResponse) *NullableTasksResponse {
	return &NullableTasksResponse{value: val, isSet: true}
}

func (v NullableTasksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


