/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HeartbeatRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeartbeatRequest{}

// HeartbeatRequest Body for `POST /api/v1/jobs/{id}/heartbeat`.
type HeartbeatRequest struct {
	// New lease duration in seconds, measured from now (1..=3600).
	ExtendSecs int32 `json:"extend_secs"`
	// The lease token returned by the lease call.
	LeaseToken string `json:"lease_token"`
}

type _HeartbeatRequest HeartbeatRequest

// NewHeartbeatRequest instantiates a new HeartbeatRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeartbeatRequest(extendSecs int32, leaseToken string) *HeartbeatRequest {
	this := HeartbeatRequest{}
	this.ExtendSecs = extendSecs
	this.LeaseToken = leaseToken
	return &this
}

// NewHeartbeatRequestWithDefaults instantiates a new HeartbeatRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeartbeatRequestWithDefaults() *HeartbeatRequest {
	this := HeartbeatRequest{}
	return &this
}

// GetExtendSecs returns the ExtendSecs field value
func (o *HeartbeatRequest) GetExtendSecs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExtendSecs
}

// GetExtendSecsOk returns a tuple with the ExtendSecs field value
// and a boolean to check if the value has been set.
func (o *HeartbeatRequest) GetExtendSecsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExtendSecs, true
}

// SetExtendSecs sets field value
func (o *HeartbeatRequest) SetExtendSecs(v int32) {
	o.ExtendSecs = v
}

// GetLeaseToken returns the LeaseToken field value
func (o *HeartbeatRequest) GetLeaseToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaseToken
}

// GetLeaseTokenOk returns a tuple with the LeaseToken field value
// and a boolean to check if the value has been set.
func (o *HeartbeatRequest) GetLeaseTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaseToken, true
}

// SetLeaseToken sets field value
func (o *HeartbeatRequest) SetLeaseToken(v string) {
	o.LeaseToken = v
}

func (o HeartbeatRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeartbeatRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["extend_secs"] = o.ExtendSecs
	toSerialize["lease_token"] = o.LeaseToken
	return toSerialize, nil
}

func (o *HeartbeatRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"extend_secs",
		"lease_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHeartbeatRequest := _HeartbeatRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHeartbeatRequest)

	if err != nil {
		return err
	}

	*o = HeartbeatRequest(varHeartbeatRequest)

	return err
}

type NullableHeartbeatRequest struct {
	value *HeartbeatRequest
	isSet bool
}

func (v NullableHeartbeatRequest) Get() *HeartbeatRequest {
	return v.value
}

func (v *NullableHeartbeatRequest) Set(val *HeartbeatRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHeartbeatRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHeartbeatRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeartbeatRequest(val *HeartbeatRequest) *NullableHeartbeatRequest {
	return &NullableHeartbeatRequest{value: val, isSet: true}
}

func (v NullableHeartbeatRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeartbeatRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


