/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"fmt"
)

// OnSuccess Reserved for future expansion; only `Continue` is meaningful today.
type OnSuccess string

// List of OnSuccess
const (
	ONSUCCESS_CONTINUE OnSuccess = "continue"
)

// All allowed values of OnSuccess enum
var AllowedOnSuccessEnumValues = []OnSuccess{
	"continue",
}

func (v *OnSuccess) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OnSuccess(value)
	for _, existing := range AllowedOnSuccessEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OnSuccess", value)
}

// NewOnSuccessFromValue returns a pointer to a valid OnSuccess
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOnSuccessFromValue(v string) (*OnSuccess, error) {
	ev := OnSuccess(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OnSuccess: valid values are %v", v, AllowedOnSuccessEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OnSuccess) IsValid() bool {
	for _, existing := range AllowedOnSuccessEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OnSuccess value
func (v OnSuccess) Ptr() *OnSuccess {
	return &v
}

type NullableOnSuccess struct {
	value *OnSuccess
	isSet bool
}

func (v NullableOnSuccess) Get() *OnSuccess {
	return v.value
}

func (v *NullableOnSuccess) Set(val *OnSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableOnSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableOnSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnSuccess(val *OnSuccess) *NullableOnSuccess {
	return &NullableOnSuccess{value: val, isSet: true}
}

func (v NullableOnSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

