/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatsSnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsSnapshot{}

// StatsSnapshot Plain snapshot of [`EngineStats`].
type StatsSnapshot struct {
	JobsCompleted int64 `json:"jobs_completed"`
	JobsCreated int64 `json:"jobs_created"`
	JobsDeadLettered int64 `json:"jobs_dead_lettered"`
	JobsFailed int64 `json:"jobs_failed"`
	JobsRetried int64 `json:"jobs_retried"`
	WorkflowsCompleted int64 `json:"workflows_completed"`
	WorkflowsCreated int64 `json:"workflows_created"`
	WorkflowsFailed int64 `json:"workflows_failed"`
}

type _StatsSnapshot StatsSnapshot

// NewStatsSnapshot instantiates a new StatsSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsSnapshot(jobsCompleted int64, jobsCreated int64, jobsDeadLettered int64, jobsFailed int64, jobsRetried int64, workflowsCompleted int64, workflowsCreated int64, workflowsFailed int64) *StatsSnapshot {
	this := StatsSnapshot{}
	this.JobsCompleted = jobsCompleted
	this.JobsCreated = jobsCreated
	this.JobsDeadLettered = jobsDeadLettered
	this.JobsFailed = jobsFailed
	this.JobsRetried = jobsRetried
	this.WorkflowsCompleted = workflowsCompleted
	this.WorkflowsCreated = workflowsCreated
	this.WorkflowsFailed = workflowsFailed
	return &this
}

// NewStatsSnapshotWithDefaults instantiates a new StatsSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsSnapshotWithDefaults() *StatsSnapshot {
	this := StatsSnapshot{}
	return &this
}

// GetJobsCompleted returns the JobsCompleted field value
func (o *StatsSnapshot) GetJobsCompleted() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.JobsCompleted
}

// GetJobsCompletedOk returns a tuple with the JobsCompleted field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetJobsCompletedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobsCompleted, true
}

// SetJobsCompleted sets field value
func (o *StatsSnapshot) SetJobsCompleted(v int64) {
	o.JobsCompleted = v
}

// GetJobsCreated returns the JobsCreated field value
func (o *StatsSnapshot) GetJobsCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.JobsCreated
}

// GetJobsCreatedOk returns a tuple with the JobsCreated field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetJobsCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobsCreated, true
}

// SetJobsCreated sets field value
func (o *StatsSnapshot) SetJobsCreated(v int64) {
	o.JobsCreated = v
}

// GetJobsDeadLettered returns the JobsDeadLettered field value
func (o *StatsSnapshot) GetJobsDeadLettered() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.JobsDeadLettered
}

// GetJobsDeadLetteredOk returns a tuple with the JobsDeadLettered field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetJobsDeadLetteredOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobsDeadLettered, true
}

// SetJobsDeadLettered sets field value
func (o *StatsSnapshot) SetJobsDeadLettered(v int64) {
	o.JobsDeadLettered = v
}

// GetJobsFailed returns the JobsFailed field value
func (o *StatsSnapshot) GetJobsFailed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.JobsFailed
}

// GetJobsFailedOk returns a tuple with the JobsFailed field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetJobsFailedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobsFailed, true
}

// SetJobsFailed sets field value
func (o *StatsSnapshot) SetJobsFailed(v int64) {
	o.JobsFailed = v
}

// GetJobsRetried returns the JobsRetried field value
func (o *StatsSnapshot) GetJobsRetried() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.JobsRetried
}

// GetJobsRetriedOk returns a tuple with the JobsRetried field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetJobsRetriedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobsRetried, true
}

// SetJobsRetried sets field value
func (o *StatsSnapshot) SetJobsRetried(v int64) {
	o.JobsRetried = v
}

// GetWorkflowsCompleted returns the WorkflowsCompleted field value
func (o *StatsSnapshot) GetWorkflowsCompleted() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WorkflowsCompleted
}

// GetWorkflowsCompletedOk returns a tuple with the WorkflowsCompleted field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetWorkflowsCompletedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowsCompleted, true
}

// SetWorkflowsCompleted sets field value
func (o *StatsSnapshot) SetWorkflowsCompleted(v int64) {
	o.WorkflowsCompleted = v
}

// GetWorkflowsCreated returns the WorkflowsCreated field value
func (o *StatsSnapshot) GetWorkflowsCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WorkflowsCreated
}

// GetWorkflowsCreatedOk returns a tuple with the WorkflowsCreated field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetWorkflowsCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowsCreated, true
}

// SetWorkflowsCreated sets field value
func (o *StatsSnapshot) SetWorkflowsCreated(v int64) {
	o.WorkflowsCreated = v
}

// GetWorkflowsFailed returns the WorkflowsFailed field value
func (o *StatsSnapshot) GetWorkflowsFailed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WorkflowsFailed
}

// GetWorkflowsFailedOk returns a tuple with the WorkflowsFailed field value
// and a boolean to check if the value has been set.
func (o *StatsSnapshot) GetWorkflowsFailedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowsFailed, true
}

// SetWorkflowsFailed sets field value
func (o *StatsSnapshot) SetWorkflowsFailed(v int64) {
	o.WorkflowsFailed = v
}

func (o StatsSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsSnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs_completed"] = o.JobsCompleted
	toSerialize["jobs_created"] = o.JobsCreated
	toSerialize["jobs_dead_lettered"] = o.JobsDeadLettered
	toSerialize["jobs_failed"] = o.JobsFailed
	toSerialize["jobs_retried"] = o.JobsRetried
	toSerialize["workflows_completed"] = o.WorkflowsCompleted
	toSerialize["workflows_created"] = o.WorkflowsCreated
	toSerialize["workflows_failed"] = o.WorkflowsFailed
	return toSerialize, nil
}

func (o *StatsSnapshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs_completed",
		"jobs_created",
		"jobs_dead_lettered",
		"jobs_failed",
		"jobs_retried",
		"workflows_completed",
		"workflows_created",
		"workflows_failed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsSnapshot := _StatsSnapshot{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatsSnapshot)

	if err != nil {
		return err
	}

	*o = StatsSnapshot(varStatsSnapshot)

	return err
}

type NullableStatsSnapshot struct {
	value *StatsSnapshot
	isSet bool
}

func (v NullableStatsSnapshot) Get() *StatsSnapshot {
	return v.value
}

func (v *NullableStatsSnapshot) Set(val *StatsSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsSnapshot(val *StatsSnapshot) *NullableStatsSnapshot {
	return &NullableStatsSnapshot{value: val, isSet: true}
}

func (v NullableStatsSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


