/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListWorkflowsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWorkflowsResponse{}

// ListWorkflowsResponse struct for ListWorkflowsResponse
type ListWorkflowsResponse struct {
	HasMore bool `json:"has_more"`
	Limit int64 `json:"limit"`
	// Opaque keyset cursor for the next page (present when `has_more`). Pass it back as `cursor` to continue where this page ended; cheaper than deep OFFSET paging.
	NextCursor NullableString `json:"next_cursor,omitempty"`
	Offset int64 `json:"offset"`
	// Exact total match count; only present when `include_total=true`.
	Total NullableInt64 `json:"total,omitempty"`
	Workflows []Workflow `json:"workflows"`
}

type _ListWorkflowsResponse ListWorkflowsResponse

// NewListWorkflowsResponse instantiates a new ListWorkflowsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWorkflowsResponse(hasMore bool, limit int64, offset int64, workflows []Workflow) *ListWorkflowsResponse {
	this := ListWorkflowsResponse{}
	this.HasMore = hasMore
	this.Limit = limit
	this.Offset = offset
	this.Workflows = workflows
	return &this
}

// NewListWorkflowsResponseWithDefaults instantiates a new ListWorkflowsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWorkflowsResponseWithDefaults() *ListWorkflowsResponse {
	this := ListWorkflowsResponse{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *ListWorkflowsResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListWorkflowsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListWorkflowsResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetLimit returns the Limit field value
func (o *ListWorkflowsResponse) GetLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ListWorkflowsResponse) GetLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ListWorkflowsResponse) SetLimit(v int64) {
	o.Limit = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListWorkflowsResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListWorkflowsResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ListWorkflowsResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *ListWorkflowsResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *ListWorkflowsResponse) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *ListWorkflowsResponse) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetOffset returns the Offset field value
func (o *ListWorkflowsResponse) GetOffset() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *ListWorkflowsResponse) GetOffsetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *ListWorkflowsResponse) SetOffset(v int64) {
	o.Offset = v
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListWorkflowsResponse) GetTotal() int64 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int64
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListWorkflowsResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *ListWorkflowsResponse) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt64 and assigns it to the Total field.
func (o *ListWorkflowsResponse) SetTotal(v int64) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *ListWorkflowsResponse) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *ListWorkflowsResponse) UnsetTotal() {
	o.Total.Unset()
}

// GetWorkflows returns the Workflows field value
func (o *ListWorkflowsResponse) GetWorkflows() []Workflow {
	if o == nil {
		var ret []Workflow
		return ret
	}

	return o.Workflows
}

// GetWorkflowsOk returns a tuple with the Workflows field value
// and a boolean to check if the value has been set.
func (o *ListWorkflowsResponse) GetWorkflowsOk() ([]Workflow, bool) {
	if o == nil {
		return nil, false
	}
	return o.Workflows, true
}

// SetWorkflows sets field value
func (o *ListWorkflowsResponse) SetWorkflows(v []Workflow) {
	o.Workflows = v
}

func (o ListWorkflowsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWorkflowsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["limit"] = o.Limit
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	toSerialize["offset"] = o.Offset
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}
	toSerialize["workflows"] = o.Workflows
	return toSerialize, nil
}

func (o *ListWorkflowsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"limit",
		"offset",
		"workflows",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListWorkflowsResponse := _ListWorkflowsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListWorkflowsResponse)

	if err != nil {
		return err
	}

	*o = ListWorkflowsResponse(varListWorkflowsResponse)

	return err
}

type NullableListWorkflowsResponse struct {
	value *ListWorkflowsResponse
	isSet bool
}

func (v NullableListWorkflowsResponse) Get() *ListWorkflowsResponse {
	return v.value
}

func (v *NullableListWorkflowsResponse) Set(val *ListWorkflowsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListWorkflowsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListWorkflowsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWorkflowsResponse(val *ListWorkflowsResponse) *NullableListWorkflowsResponse {
	return &NullableListWorkflowsResponse{value: val, isSet: true}
}

func (v NullableListWorkflowsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWorkflowsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


