/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateJobRequest{}

// CreateJobRequest struct for CreateJobRequest
type CreateJobRequest struct {
	Config NullableJobConfigRequest `json:"config,omitempty"`
	// Arbitrary JSON object passed to the handler.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Don't run before this instant (RFC 3339). The job is created immediately but stays invisible to workers until then.
	RunAt NullableTime `json:"run_at,omitempty"`
	// The registered task handler to invoke.
	TaskName string `json:"task_name"`
}

type _CreateJobRequest CreateJobRequest

// NewCreateJobRequest instantiates a new CreateJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateJobRequest(taskName string) *CreateJobRequest {
	this := CreateJobRequest{}
	this.TaskName = taskName
	return &this
}

// NewCreateJobRequestWithDefaults instantiates a new CreateJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateJobRequestWithDefaults() *CreateJobRequest {
	this := CreateJobRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateJobRequest) GetConfig() JobConfigRequest {
	if o == nil || IsNil(o.Config.Get()) {
		var ret JobConfigRequest
		return ret
	}
	return *o.Config.Get()
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateJobRequest) GetConfigOk() (*JobConfigRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Config.Get(), o.Config.IsSet()
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateJobRequest) HasConfig() bool {
	if o != nil && o.Config.IsSet() {
		return true
	}

	return false
}

// SetConfig gets a reference to the given NullableJobConfigRequest and assigns it to the Config field.
func (o *CreateJobRequest) SetConfig(v JobConfigRequest) {
	o.Config.Set(&v)
}
// SetConfigNil sets the value for Config to be an explicit nil
func (o *CreateJobRequest) SetConfigNil() {
	o.Config.Set(nil)
}

// UnsetConfig ensures that no value is present for Config, not even an explicit nil
func (o *CreateJobRequest) UnsetConfig() {
	o.Config.Unset()
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *CreateJobRequest) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *CreateJobRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *CreateJobRequest) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetRunAt returns the RunAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateJobRequest) GetRunAt() time.Time {
	if o == nil || IsNil(o.RunAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAt.Get()
}

// GetRunAtOk returns a tuple with the RunAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateJobRequest) GetRunAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAt.Get(), o.RunAt.IsSet()
}

// HasRunAt returns a boolean if a field has been set.
func (o *CreateJobRequest) HasRunAt() bool {
	if o != nil && o.RunAt.IsSet() {
		return true
	}

	return false
}

// SetRunAt gets a reference to the given NullableTime and assigns it to the RunAt field.
func (o *CreateJobRequest) SetRunAt(v time.Time) {
	o.RunAt.Set(&v)
}
// SetRunAtNil sets the value for RunAt to be an explicit nil
func (o *CreateJobRequest) SetRunAtNil() {
	o.RunAt.Set(nil)
}

// UnsetRunAt ensures that no value is present for RunAt, not even an explicit nil
func (o *CreateJobRequest) UnsetRunAt() {
	o.RunAt.Unset()
}

// GetTaskName returns the TaskName field value
func (o *CreateJobRequest) GetTaskName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value
// and a boolean to check if the value has been set.
func (o *CreateJobRequest) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskName, true
}

// SetTaskName sets field value
func (o *CreateJobRequest) SetTaskName(v string) {
	o.TaskName = v
}

func (o CreateJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config.IsSet() {
		toSerialize["config"] = o.Config.Get()
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if o.RunAt.IsSet() {
		toSerialize["run_at"] = o.RunAt.Get()
	}
	toSerialize["task_name"] = o.TaskName
	return toSerialize, nil
}

func (o *CreateJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateJobRequest := _CreateJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateJobRequest)

	if err != nil {
		return err
	}

	*o = CreateJobRequest(varCreateJobRequest)

	return err
}

type NullableCreateJobRequest struct {
	value *CreateJobRequest
	isSet bool
}

func (v NullableCreateJobRequest) Get() *CreateJobRequest {
	return v.value
}

func (v *NullableCreateJobRequest) Set(val *CreateJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateJobRequest(val *CreateJobRequest) *NullableCreateJobRequest {
	return &NullableCreateJobRequest{value: val, isSet: true}
}

func (v NullableCreateJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


