/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCronsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCronsResponse{}

// ListCronsResponse struct for ListCronsResponse
type ListCronsResponse struct {
	Crons []CronSchedule `json:"crons"`
	HasMore bool `json:"has_more"`
	Limit int64 `json:"limit"`
	// Opaque keyset cursor for the next page (present when `has_more`). Pass it back as `cursor` to continue where this page ended; cheaper than deep OFFSET paging.
	NextCursor NullableString `json:"next_cursor,omitempty"`
	Offset int64 `json:"offset"`
	// Exact total match count; only present when `include_total=true`.
	Total NullableInt64 `json:"total,omitempty"`
}

type _ListCronsResponse ListCronsResponse

// NewListCronsResponse instantiates a new ListCronsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCronsResponse(crons []CronSchedule, hasMore bool, limit int64, offset int64) *ListCronsResponse {
	this := ListCronsResponse{}
	this.Crons = crons
	this.HasMore = hasMore
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewListCronsResponseWithDefaults instantiates a new ListCronsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCronsResponseWithDefaults() *ListCronsResponse {
	this := ListCronsResponse{}
	return &this
}

// GetCrons returns the Crons field value
func (o *ListCronsResponse) GetCrons() []CronSchedule {
	if o == nil {
		var ret []CronSchedule
		return ret
	}

	return o.Crons
}

// GetCronsOk returns a tuple with the Crons field value
// and a boolean to check if the value has been set.
func (o *ListCronsResponse) GetCronsOk() ([]CronSchedule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Crons, true
}

// SetCrons sets field value
func (o *ListCronsResponse) SetCrons(v []CronSchedule) {
	o.Crons = v
}

// GetHasMore returns the HasMore field value
func (o *ListCronsResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListCronsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListCronsResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetLimit returns the Limit field value
func (o *ListCronsResponse) GetLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ListCronsResponse) GetLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ListCronsResponse) SetLimit(v int64) {
	o.Limit = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListCronsResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListCronsResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ListCronsResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *ListCronsResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *ListCronsResponse) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *ListCronsResponse) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetOffset returns the Offset field value
func (o *ListCronsResponse) GetOffset() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *ListCronsResponse) GetOffsetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *ListCronsResponse) SetOffset(v int64) {
	o.Offset = v
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListCronsResponse) GetTotal() int64 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int64
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListCronsResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *ListCronsResponse) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt64 and assigns it to the Total field.
func (o *ListCronsResponse) SetTotal(v int64) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *ListCronsResponse) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *ListCronsResponse) UnsetTotal() {
	o.Total.Unset()
}

func (o ListCronsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCronsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["crons"] = o.Crons
	toSerialize["has_more"] = o.HasMore
	toSerialize["limit"] = o.Limit
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	toSerialize["offset"] = o.Offset
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}
	return toSerialize, nil
}

func (o *ListCronsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"crons",
		"has_more",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCronsResponse := _ListCronsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCronsResponse)

	if err != nil {
		return err
	}

	*o = ListCronsResponse(varListCronsResponse)

	return err
}

type NullableListCronsResponse struct {
	value *ListCronsResponse
	isSet bool
}

func (v NullableListCronsResponse) Get() *ListCronsResponse {
	return v.value
}

func (v *NullableListCronsResponse) Set(val *ListCronsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListCronsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListCronsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCronsResponse(val *ListCronsResponse) *NullableListCronsResponse {
	return &NullableListCronsResponse{value: val, isSet: true}
}

func (v NullableListCronsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCronsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


