/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeaseJobsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeaseJobsResponse{}

// LeaseJobsResponse struct for LeaseJobsResponse
type LeaseJobsResponse struct {
	Jobs []LeasedJob `json:"jobs"`
}

type _LeaseJobsResponse LeaseJobsResponse

// NewLeaseJobsResponse instantiates a new LeaseJobsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaseJobsResponse(jobs []LeasedJob) *LeaseJobsResponse {
	this := LeaseJobsResponse{}
	this.Jobs = jobs
	return &this
}

// NewLeaseJobsResponseWithDefaults instantiates a new LeaseJobsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaseJobsResponseWithDefaults() *LeaseJobsResponse {
	this := LeaseJobsResponse{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *LeaseJobsResponse) GetJobs() []LeasedJob {
	if o == nil {
		var ret []LeasedJob
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *LeaseJobsResponse) GetJobsOk() ([]LeasedJob, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *LeaseJobsResponse) SetJobs(v []LeasedJob) {
	o.Jobs = v
}

func (o LeaseJobsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeaseJobsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs
	return toSerialize, nil
}

func (o *LeaseJobsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeaseJobsResponse := _LeaseJobsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeaseJobsResponse)

	if err != nil {
		return err
	}

	*o = LeaseJobsResponse(varLeaseJobsResponse)

	return err
}

type NullableLeaseJobsResponse struct {
	value *LeaseJobsResponse
	isSet bool
}

func (v NullableLeaseJobsResponse) Get() *LeaseJobsResponse {
	return v.value
}

func (v *NullableLeaseJobsResponse) Set(val *LeaseJobsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaseJobsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaseJobsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaseJobsResponse(val *LeaseJobsResponse) *NullableLeaseJobsResponse {
	return &NullableLeaseJobsResponse{value: val, isSet: true}
}

func (v NullableLeaseJobsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaseJobsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


