/*
QueueFlow API

REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package queueflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBatchJobsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBatchJobsResponse{}

// CreateBatchJobsResponse struct for CreateBatchJobsResponse
type CreateBatchJobsResponse struct {
	Count int32 `json:"count"`
	JobIds []string `json:"job_ids"`
}

type _CreateBatchJobsResponse CreateBatchJobsResponse

// NewCreateBatchJobsResponse instantiates a new CreateBatchJobsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBatchJobsResponse(count int32, jobIds []string) *CreateBatchJobsResponse {
	this := CreateBatchJobsResponse{}
	this.Count = count
	this.JobIds = jobIds
	return &this
}

// NewCreateBatchJobsResponseWithDefaults instantiates a new CreateBatchJobsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBatchJobsResponseWithDefaults() *CreateBatchJobsResponse {
	this := CreateBatchJobsResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *CreateBatchJobsResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *CreateBatchJobsResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *CreateBatchJobsResponse) SetCount(v int32) {
	o.Count = v
}

// GetJobIds returns the JobIds field value
func (o *CreateBatchJobsResponse) GetJobIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.JobIds
}

// GetJobIdsOk returns a tuple with the JobIds field value
// and a boolean to check if the value has been set.
func (o *CreateBatchJobsResponse) GetJobIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobIds, true
}

// SetJobIds sets field value
func (o *CreateBatchJobsResponse) SetJobIds(v []string) {
	o.JobIds = v
}

func (o CreateBatchJobsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBatchJobsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["job_ids"] = o.JobIds
	return toSerialize, nil
}

func (o *CreateBatchJobsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"job_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBatchJobsResponse := _CreateBatchJobsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBatchJobsResponse)

	if err != nil {
		return err
	}

	*o = CreateBatchJobsResponse(varCreateBatchJobsResponse)

	return err
}

type NullableCreateBatchJobsResponse struct {
	value *CreateBatchJobsResponse
	isSet bool
}

func (v NullableCreateBatchJobsResponse) Get() *CreateBatchJobsResponse {
	return v.value
}

func (v *NullableCreateBatchJobsResponse) Set(val *CreateBatchJobsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBatchJobsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBatchJobsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBatchJobsResponse(val *CreateBatchJobsResponse) *NullableCreateBatchJobsResponse {
	return &NullableCreateBatchJobsResponse{value: val, isSet: true}
}

func (v NullableCreateBatchJobsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBatchJobsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


